The UBL extension to be used for below elements can be found <<_cacbillingreference, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/BillingReferenceExtension`.

*Example* +
_Example below how the URI is used for this extension._
[source,xml]
----
<Invoice>
    <!-- Code omitted for clarity -->
    <cac:BillingReference>
        <cac:InvoiceDocumentReference>
            <ext:UBLExtensions>
                <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:BillingReferenceExtension</ext:ExtensionURI> <!--1-->
                    <ext:ExtensionContent>
                        <puf:PageroExtension>
                            <puf:BillingReferenceExtension/> <!--2-->
                        </puf:PageroExtension>
                    </ext:ExtensionContent>
                </ext:UBLExtension>
            </ext:UBLExtensions>
        </cac:InvoiceDocumentReference>
    </cac:BillingReference>
    <!-- Code omitted for clarity -->
</Invoice>

----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

.Elements added in puf:BillingReferenceExtension
|===
|Element |Description

|`puf:InvoiceSeries/cbc:ID`
|**Billing reference document series identifier** +
Identifier used for the series the referenced document is part of. 

|`cbc:Note`
|**Billing reference note** +
Textual note describing the reason for issuing a credit/debit note.

|`puf:Code`
|**Billing reference code** +
Code signifying the reason for credit.

|`puf:ClearanceID`
|**Clearance ID of the referenced document** +
ID, usually assigned by the Tax Authority, of the referenced document e.g. UUID in Malaysia.

|`puf:RestrictedInformation`
|**Restricted information** +
Key-value pairs for additional country-specific information related to the billing reference. Can be repeated multiple times.

|`cbc:TaxableAmount`
|**Referenced document tax base amount** +
The tax base amount of the referenced document. Used in some countries for corrections (e.g., Spain substitutive method).

|`cbc:TaxAmount`
|**Referenced document tax amount** +
The tax amount of the referenced document. Used in some countries for corrections (e.g., Spain substitutive method).

|`puf:EquivalenceSurchargeAmount`
|**Referenced document equivalence surcharge amount** +
The equivalence surcharge amount of the referenced document. Used in Spain for corrections when equivalence surcharge applies.
|===

*Example* +
_Invoice document reference ID, date and extension_
[source,xml]
----
<Invoice>
    <!-- Code omitted for clarity -->
    <cac:BillingReference>
        <cac:InvoiceDocumentReference>
            <ext:UBLExtensions>
                <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:BillingReferenceExtension</ext:ExtensionURI>
                    <ext:ExtensionContent>
                        <puf:PageroExtension>
                            <puf:BillingReferenceExtension>
                                <!-- Referenced invoice's serie, if applicable -->
                                <puf:InvoiceSeries>
                                    <cbc:ID>InvSeries1</cbc:ID>
                                </puf:InvoiceSeries>
                                <cbc:Note>Textual note describing the reason for issuing a credit/debit note</cbc:Note>
                                <!-- Reason for credit in code form, if applicable -->
                                <puf:Code>codeValue</puf:Code>
                                <puf:ClearanceID>Clearance ID</puf:ClearanceID>
                                <!-- Additional country-specific information, if applicable -->
                                <puf:RestrictedInformation>
                                    <puf:Key>CountrySpecificKey</puf:Key>
                                    <puf:Value>CountrySpecificValue</puf:Value>
                                </puf:RestrictedInformation>
                                <!-- Referenced document amounts, if applicable (e.g., Spain substitutive corrections) -->
                                <cbc:TaxableAmount currencyID="EUR">1000.00</cbc:TaxableAmount>
                                <cbc:TaxAmount currencyID="EUR">210.00</cbc:TaxAmount>
                                <puf:EquivalenceSurchargeAmount currencyID="EUR">52.00</puf:EquivalenceSurchargeAmount>
                            </puf:BillingReferenceExtension>
                        </puf:PageroExtension>
                    </ext:ExtensionContent>
                </ext:UBLExtension>
            </ext:UBLExtensions>
            <cbc:ID>Invoice reference ID</cbc:ID>
            <cbc:IssueDate>2021-01-01</cbc:IssueDate>
        </cac:InvoiceDocumentReference>
    </cac:BillingReference>
    <!-- Code omitted for clarity -->
</Invoice>
----
