The UBL extension to be used for below elements can be found <<_caccontractdocumentreference, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/ContractDocumentReferenceExtension`.

*Example* +
_Example below how the URI is used for this extension._
[source,xml]
----
<Invoice>
    <!-- Code omitted for clarity -->
    <cac:ContractDocumentReference>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:ContractDocumentReferenceExtension</ext:ExtensionURI> <!--1-->
                <ext:ExtensionContent>
                    <puf:PageroExtension>
                        <puf:ContractDocumentReferenceExtension/> <!--2-->
                    </puf:PageroExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
    </cac:ContractDocumentReference>
    <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

.Elements added in puf:ContractDocumentReferenceExtension
|===
|Element |Description

|`puf:BuyerContractID`
|**Buyer contract identifier** +
ID for the buyer referenced contract document.

|`puf:BuyerContractIssueDate`
|**Buyer contract issue date** +
Issue date for the buyer referenced contract document, date should be formatted yyyy-mm-dd.

|===

*Example* +
_Contract document reference ID, date and extension_
[source,xml]
----
<Invoice>
    <!-- Code omitted for clarity -->
    <cac:ContractDocumentReference>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:ContractDocumentReferenceExtension</ext:ExtensionURI>
                <ext:ExtensionContent>
                    <puf:PageroExtension>
                        <puf:ContractDocumentReferenceExtension>
                            <puf:BuyerContractID>BuyerContractID</puf:BuyerContractID>
                            <puf:BuyerContractIssueDate>2019-01-01</puf:BuyerContractIssueDate>
                        </puf:ContractDocumentReferenceExtension>
                    </puf:PageroExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:ID>Contract Document ID</cbc:ID>
        <cbc:IssueDate>2019-01-01</cbc:IssueDate>
    </cac:ContractDocumentReference>
    <!-- Code omitted for clarity -->
</Invoice>
----
