The UBL extension to be used for below elements can be found <<_cacdelivery, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/DeliveryExtension`.

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:Delivery>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DeliveryExtension</ext:ExtensionURI> <!--1-->
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:DeliveryExtension/> <!--2-->
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:Delivery>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table show the definition of the additional elements added to the delivery extension.

.Elements added in puf:DeliveryExtension
|===
|Element |Description

|`puf:PortCode`
|**Dispatch port code** +
A code for the dispatch port code.

|`puf:DeliveryMethod/cbc:Note`
|**Delivery method note** +
Description of the delivery method (free text).

|`puf:DeliveryMethod/puf:Code`
|**Delivery method code** +
A code for the delivery method.

|===

*Example 1* +
_Delivery method and code defined_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:Delivery>
      <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DeliveryExtension</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:DeliveryExtension>
                        <puf:DeliveryMethod>
                            <cbc:Note>Text describing the delivery method</cbc:Note>
                            <puf:Code>Deliver Method Code</puf:Code>
                        </puf:DeliveryMethod>
                    </puf:DeliveryExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:Delivery>
  <!-- Code omitted for clarity -->
</Invoice>
----

*Example 2* +
_Dispatch port code_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:Delivery>
      <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DeliveryExtension</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:DeliveryExtension>
                            <puf:PortCode>Dispatch Port Code</puf:PortCode>
                    </puf:DeliveryExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:Delivery>
  <!-- Code omitted for clarity -->
</Invoice>
----
