In order to specify if IGST (Integrated Goods and Services Tax) is applicable on intra state supplies the following elements has been added in the below extension.

The UBL extension to be used for below elements can be found <<_extublextensions, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/IGSTOnIntra`.

See example below as well as the URI to be used for this extension.

*Example* +
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:IGSTOnIntra</ext:ExtensionURI> <!--1-->
          <ext:ExtensionContent>
              <puf:PageroExtension>
                <puf:IGSTOnIntra/> <!--2-->
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:PageroExtension
|===
|Element |Description

|`puf:IGSTOnIntra`
|**Indicator if IGST is applicable for intra state supplies** +
To indicate if supply is chargeable to IGST despite the fact that the Supplier and Recipient are located within same State. +
_Possible value is true or false._

|===

*Example* +
_IGST on intra state supplies_
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:IGSTOnIntra</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                  <puf:IGSTOnIntra>true</puf:IGSTOnIntra>
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</Invoice>
----
