RestrictedInformation has been added on document level in order to cater the need for unique country specific data and internal customer information that might be required for internal processing. +

WARNING: Note that no customer specific information can be added without prior consulting with Pagero. +
If country specific information is available as restricted information value, this can be found in the Country specifics section.

The UBL extension to be used for below elements can be found <<_extublextensions, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/RestrictedInformation`.

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:RestrictedInformation</ext:ExtensionURI> <!--1-->
          <ext:ExtensionContent>
              <puf:PageroExtension>
                <puf:RestrictedInformation/> <!--2-->
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table show the definition of the new element added to the extension.

.Elements added in puf:RestrictedInformation
|===
|Element |Description

|`puf:Key`
|**Key** +
Key defining the type of value.

|`puf:Value`
|**Value** +
Value relevant to the assigned key.

|===

*Example* +
_RestrictedInformation example from Hungary specific section_
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
    <ext:UBLExtension>
        <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:RestrictedInformation</ext:ExtensionURI>
        <ext:ExtensionContent>
            <puf:PageroExtension>
              <puf:RestrictedInformation>
                  <puf:Key>modifyWithoutMaster</puf:Key>
                  <puf:Value>false</puf:Value>
              </puf:RestrictedInformation>
            </puf:PageroExtension>
        </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</Invoice>
----
