RestrictedInformationParty has been added on document level in order to cater the need for additional country specific parties

WARNING: Note that no customer specific information can be added without prior consulting with Pagero. +
If country specific information is available as restricted information party, this can be found in the Country specifics section.

The UBL extension to be used for below elements can be found <<_extublextensions, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/RestrictedInformationParty`. 

See example below as well as the URI to be used for this extension.

*Example* +
[source,xml]
----
<Invoice>
    <ext:UBLExtensions>
            <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:RestrictedInformationParty</ext:ExtensionURI> <!--1-->
                    <ext:ExtensionContent>
                            <puf:PageroExtension>
                                <puf:RestrictedInformationParty>
                                    <puf:Key>dummy-key</puf:Key>
                                    <cbc:Description>Party description</cbc:Description>
                                    <cac:Party>
                                        <cac:PartyIdentification>
                                            <cbc:ID schemeID="0088">1234567890123</cbc:ID>
                                        </cac:PartyIdentification>
                                    <cac:Party>
                                </puf:RestrictedInformationParty> <!--2-->
                            </puf:PageroExtension>
                    </ext:ExtensionContent>
            </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:PageroExtension/puf:RestrictedInformationParty
|===
|Element |Description

|`puf:Key`
|**Key identifying the party** +
Key describing the restricted party.

|`cbc:Description`
|**Description of the party** +
The description of the role of the restricted party.

|`cac:Party/cac:PartyIdentification/cbc:ID`
|**Party identification** +
Restricted party identification.

|`cac:Party/cac:PartyName/cbc:Name`
|**Party name** +
Restricted party name.

|`cac:Party/cac:PostalAddress/cbc:StreetName`
|**Street name** +
Restricted party postal address street name.

|`cac:Party/cac:PostalAddress/cbc:BuildingNumber`
|**Building number** +
Restricted party postal address building number.

|`cac:Party/cac:PostalAddress/cbc:CityName`
|**City name** +
Restricted party postal address city name.

|`cac:Party/cac:PostalAddress/cbc:PostalZone`
|**Postal zone** +
Restricted party postal address postal zone.

|`cac:Party/cac:PostalAddress/cbc:CountrySubentity`
|**Country subentity** +
Restricted party postal address country subentity.

|`cac:Party/cac:PostalAddress/cac:Country/cbc:IdentificationCode`
|**Country code** +
Restricted party postal address country identification code.

|`cac:Party/cac:PartyTaxScheme/cbc:CompanyID`
|**Tax registration identifier** +
Restricted party tax registration identifier.

|`cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:ID`
|**Tax scheme** +
Restricted party tax scheme identifier.

|`cac:Party/cac:PartyLegalEntity/cbc:RegistrationName`
|**Registration name** +
Restricted party legal registration name.

|===

*Example* +
_Restricted Information Party_
[source,xml]
----
<Invoice>
    <ext:UBLExtensions>
            <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:RestrictedInformationParty</ext:ExtensionURI>
                    <ext:ExtensionContent>
                            <puf:PageroExtension>
                                <puf:RestrictedInformationParty>
                                    <puf:Key>dummy-key</puf:Key>
                                    <cbc:Description>Party description</cbc:Description>
                                    <cac:Party>
                                        <cac:PartyIdentification>
                                            <cbc:ID schemeID="0088">1234567890123</cbc:ID>
                                        </cac:PartyIdentification>
                                        <cac:PartyName>
                                            <cbc:Name>Dummy Company Name</cbc:Name>
                                        </cac:PartyName>
                                        <cac:PostalAddress>
                                            <cbc:StreetName>Dummy Street 1</cbc:StreetName>
                                            <cbc:BuildingNumber>10A</cbc:BuildingNumber>
                                            <cbc:CityName>Dummy City</cbc:CityName>
                                            <cbc:PostalZone>12345</cbc:PostalZone>
                                            <cbc:CountrySubentity>Region</cbc:CountrySubentity>
                                            <cac:Country>
                                                <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                                            </cac:Country>
                                        </cac:PostalAddress>
                                        <cac:PartyTaxScheme>
                                            <cbc:CompanyID>9999999999</cbc:CompanyID>
                                            <cac:TaxScheme>
                                                <cbc:ID>VAT</cbc:ID>
                                            </cac:TaxScheme>
                                        </cac:PartyTaxScheme>
                                        <cac:PartyLegalEntity>
                                            <cbc:RegistrationName>Name</cbc:RegistrationName>
                                        </cac:PartyLegalEntity>
                                    </cac:Party>
                                </puf:RestrictedInformationParty>
                            </puf:PageroExtension>
                    </ext:ExtensionContent>
            </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</Invoice>

----
