In order to indicate that the document is self-billed, a segment for this is added as Extension.

WARNING: Note that not all markets are supported in Pagero Online. +
Please contact Pagero to learn in which markets we support self-billing.

The UBL extension to be used for below elements can be found <<_extublextensions, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/SelfBilled`. 

See example below as well as the URI to be used for this extension.

*Example* +
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:SelfBilled</ext:ExtensionURI> <!--1-->
          <ext:ExtensionContent>
              <puf:PageroExtension>
                <puf:SelfBilled/> <!--2-->
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:PageroExtension/puf:SelfBilled
|===
|Element |Description

|`puf:SelfBilled`
|**Self-Billing Indicator** +
Can either be *true* or *false*. +
**Note that if the element is missing Pagero Online treat it as false**

|===

*Example* +
_Self Billed_
[source,xml]
----
<Invoice>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:SelfBilled</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:SelfBilled>true</puf:SelfBilled>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</Invoice>

----
