In order to provide a supplier generated QR string following elements has been added in the below extension.

The UBL extension to be used for below elements can be found <<_extublextensions, here>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/QRExtension`.

See example below as well as the URI to be used for this extension.

*Example* +
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:QRExtension</ext:ExtensionURI> <!--1-->
          <ext:ExtensionContent>
              <puf:PageroExtension>
                <puf:SupplierGeneratedQRString> <!--2-->
                    <puf:QRString>TheQRCode</puf:QRString>
                    <puf:QREncodingType>TEXT</puf:QREncodingType>
                </puf:SupplierGeneratedQRString> 
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:PageroExtension
|===
|Element |Description

|`puf:SupplierGeneratedQRString/puf:QRString`
|Supplier generated QR string

|`puf:SupplierGeneratedQRString/puf:QREncodingType`
|Value must be **TEXT** or **BASE64** depending on if the QR string is expressed as a text string or base 64 encoded

|===

*Example* +
_QR string provided as plain text_
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:IGSTOnIntra</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                    <puf:SupplierGeneratedQRString>
                        <puf:QRString>TheQRCode</puf:QRString>
                        <puf:QREncodingType>TEXT</puf:QREncodingType>
                    </puf:SupplierGeneratedQRString>
                </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</Invoice>
----
