Below table show available fields in `cac:Price`, note that additional elements has also been added to the extension available in <<_price>>.

.Elements added in cac:InvoiceLine/cac:Price
|===
|Path |Description

|`ext:UBLExtensions`
|**Extension Content** +
Extension is added to provide additional information in the `cac:Price` element, the information available can be found <<_price, here>>
|`cbc:PriceAmount`
|**Item net price** +
Net price of the item, this value must not be negative.
|`cbc:PriceAmount/@currencyID`
|**Item net price currency** +
Currency applied for cbc:PriceAmount, must be the same as cbc:DocumentCurrencyCode. +
For valid values see code list <<_puf_004_currencycode>>
|`cbc:BaseQuantity`
|**Base quantity** +
The number of items to which the price applies.
|`cbc:BaseQuantity/@unitCode`
|**Base quantity unit of measure** +
The unit of measure of the base quantity. +
See code list <<_puf_014_uomcode>> for recommendations
|`cac:AllowanceCharge/cbc:ChargeIndicator`
|**Charge indicator** +
Only allowance is allowed for cac:Price segment, this value must be "false".
|`cac:AllowanceCharge/cbc:Amount`
|**Allowance Amount** +
The allowance applied to the price, note that this value is just informative and the allowance amount should already been subtracted in cbc:PriceAmount element.
|`cac:AllowanceCharge/cbc:Amount/@currencyID`
|**Allowance Amount currency** +
Currency applied for cbc:Amount, must be the same as cbc:DocumentCurrencyCode. +
For valid values see code list <<_puf_004_currencycode>>
|`cac:AllowanceCharge/cbc:BaseAmount`
|**Base amount** +
The items base price, before any allowance was applied, this value must not be negative.
|`cac:AllowanceCharge/cbc:BaseAmount/@currencyID`
|**Base amount currency** +
Currency applied for cbc:BaseAmount, must be the same as cbc:DocumentCurrencyCode. +
For valid values see code list <<_puf_004_currencycode>>
|===

*Example* +
_cac:InvoiceLine/cac:Price example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
    <!-- Code omitted for clarity -->
    <cac:Price>
      <cbc:PriceAmount currencyID="EUR">100.00</cbc:PriceAmount>
      <cbc:BaseQuantity unitCode="EA">1</cbc:BaseQuantity>
      <cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
        <cbc:Amount currencyID="EUR">10</cbc:Amount>
        <cbc:BaseAmount currencyID="EUR">110.00</cbc:BaseAmount>
      </cac:AllowanceCharge>
    </cac:Price>
    <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
