Pagero Universal Format, hereafter referred to as "PUF", is developed and maintained by https://www.pagero.com/[Pagero Group^]. 

PUF is based upon https://docs.oasis-open.org/ubl/UBL-2.1.html[Universal Business Language Version 2.1 (UBL 2.1)^].

To align with new regulations and the business needs that comes with the growing use of electronic invoices throughout the world, the core idea of PUF is to enable its users to provide enough data to meet the requirements in these markets. +

To be able to provide the broadest support possible, PUF has been designed with the following core basis in mind:

* https://standards.cen.eu/dyn/www/f?p=204:110:0::::FSP_PROJECT:60602&cs=1B61B766636F9FB34B7DBD72CE9026C72[European standard EN 16931-1:2017^]

** EN 16931-1:2017 complies with the European Directive on electronic invoicing for public authorities (EN 2014/55 / ​​EU). It has been prepared by the https://en.m.wikipedia.org/wiki/CEN/TC_434[Technical Committee TC434^] at CEN by the https://commission.europa.eu/index_en[European Commission^].

*	http://docs.peppol.eu/poacc/billing/3.0/[Peppol BIS Billing 3.0^] (OpenPeppol's CIUS (Core Invoice Usage Specification) with EN16931 as the underlying specification).

*	Other https://ec.europa.eu/cefdigital/wiki/display/EINVCOMMUNITY/Community-driven+Registry+of+CIUS+(Core+Invoice+Usage+Specifications)+and+Extensions[CIUS's^] based on the regulations of https://standards.cen.eu/dyn/www/f?p=204:110:0::::FSP_PROJECT:60602&cs=1B61B766636F9FB34B7DBD72CE9026C72[EN 16931-1:2017^].

* https://ec.europa.eu/cefdigital/wiki/display/EINVCOMMUNITY/Community-driven+Registry+of+CIUS+(Core+Invoice+Usage+Specifications)+and+Extensions[Extensions^] based on the regulations of https://standards.cen.eu/dyn/www/f?p=204:110:0::::FSP_PROJECT:60602&cs=1B61B766636F9FB34B7DBD72CE9026C72[EN 16931-1:2017^].

*	Country specific information found in domestic formats in various legal domains.

Based on extensive analysis of the above, PUF has been designed to meet these country-, industry-, format- and/or system-specific requirements.

Another intention of PUF has been to create a flexible, extendable format which can be updated quickly to be able to meet the requirements of the fast-changing global electronic document landscape.

PUF is not to be considered a CIUS based on EN16931 or any other CIUS or format. PUF will, however, to a large extent try to follow the work done in EN16931, Peppol and other UBL based invoicing specifications. 

If one can create a valid and syntactically correct EN16931 based UBL-format; the threshold for implementing PUF should be negligible.

=== Version and changelog

.Version
|===
|Version |Date |Description

|2.0 |2021-06-01 |Second version published.
|1.0 |2019-05-02 |First version published.
|===
