The aim for PUF is to cover invoicing and business requirements in legal domains and countries all over the world.

The below list should be seen as an overview to visualize where PUF currently is considered applicable. If the country is marked as supported
means that an analysis of country or regional requirements has been made. It does, however, not automatically mean that all conceivable
content requirements are supported within PUF.

If a country is not in the list does not necessarily mean that PUF cannot be used in the specific region but it means that
no extensive analysis has been done of the requirements.

The list of supported countries/regions are updated continuously as PUF is developed to follow new identified markets/requirements.

=== Country list

The following list gives an overview of country support in PUF.

NOTE: The "Require ext:UBLExtensions"-column indicates whether or not the use of UBL extensions is required to be able to comply with the country requirements.

.Table of supported countries
[%autowidth.stretch]
|===
|Country |Supported by PUF |Require ext:UBLExtensions? |Comment

|Australia
|*Yes*
|*No*
|

|Austria
|*Yes*
|*No*
|

|Belgium
|*Yes*
|*No*
|

|Bulgaria
|*Yes*
|*No*
|

|Canada
|*Yes*
|*No*
|

|Croatia
|*Yes*
|*No*
|

|Denmark
|*Yes*
|*No*
|

|Estonia
|*Yes*
|*No*
|

|Finland
|*Yes*
|*No*
|

|France
|*Yes*
|*Yes*
|

|Germany
|*Yes*
|*No*
|

|Hungary
|*Yes*
|*Yes*
|

|India
|*Yes*
|*Yes*
|

|Ireland
|*Yes*
|*No*
|

|Italy
|*Yes*
|*Yes*
|

|Lithuania
|*Yes*
|*No*
|

|Luxembourg
|*Yes*
|*No*
|

|Malta
|*Yes*
|*No*
|

|Netherlands
|*Yes*
|*No*
|Only invoice and credit note support.

|New Zealand
|*Yes*
|*No*
|

|Norway
|*Yes*
|*No*
|

|Portugal
|*Yes*
|*Yes*
|

|Saudi Arabia
|*Yes*
|*Yes*
|

|Serbia
|*Yes*
|*No*
|Only standard invoice, credit note and debit note support.

|Singapore
|*Yes*
|*No*
|

|Spain
|*Yes*
|*Yes*
|

|Spain (Basque Country)
|*Yes*
|*Yes*
|Support for TicketBAI system in the Basque region. +
Only support for invoice and corrections.

|Sweden
|*Yes*
|*No*
|

|United Kingdom
|*Yes*
|*No*
|

|===
