Element `TaxCurrencyLineExtensionAmount` has been added in order to specify the lines net amount in tax currency.

The UBL extension to be used for TaxCurrencyLineExtensionAmount on line level is <<line-extension>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/LineExtension`.

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI> <!--1-->
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension/> <!--2-->
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:LineExtension
|===
|Element |Description

|`puf:TaxCurrencyLineExtensionAmount`
|**Tax currency line net amount** +
Net amount in tax currency.

|`puf:TaxCurrencyLineExtensionAmount/@currencyID`
|**Tax currency line net amount currency code** +
Currency of the `puf:TaxCurrencyLineExtensionAmount`. +
For valid values see code list <<_puf_004_currencycode>>.

|===

*Example* +
_Line with both net amount in document currency and tax currency_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI>
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension>
                          <puf:TaxCurrencyLineExtensionAmount currencyID="USD">117.00</puf:TaxCurrencyLineExtensionAmount> <!--1-->
                      </puf:LineExtension>
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <cbc:LineExtensionAmount currencyID="EUR">100.00</cbc:LineExtensionAmount> <!--2-->
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> The net amount in tax currency
<2> The net amount in document currency
