In order to specify the tender reference on line level, Originator document reference has been added to line extension.

The UBL extension to be used for OriginatorDocumentReference on line level is <<line-extension>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/LineExtension`.

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI> <!--1-->
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension>
                          <puf:OriginatorDocumentReference/> <!--2-->
                      </puf:LineExtension>
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:LineExtension/puf:OriginatorDocumentReference
|===
|Element |Description

|`cbc:ID`
|**Tender reference identifer** +
Identification of the tender reference.

|`cbc:IssueDate`
|**Referenced tender issue date** +
Date of issue of the referenced tender, date should be formatted "yyyy-mm-dd".

|===

*Example* +
_Originator document reference ID and date_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI>
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension>
                          <puf:OriginatorDocumentReference>
                              <cbc:ID>123456</cbc:ID>
                              <cbc:IssueDate>2018-01-01</cbc:IssueDate>
                          </puf:OriginatorDocumentReference>
                      </puf:LineExtension>
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
