In order to specify the contract information on line level, ContractDocumentReference has been added to Line extension.

The UBL extension to be used for ContractDocumentReference on line level is <<line-extension>>.

The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/LineExtension`.

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI> <!--1-->
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension>
                          <puf:ContractDocumentReference/> <!--2-->
                      </puf:LineExtension>
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:LineExtension/puf:ContractDocumentReference
|===
|Element |Description

|`cbc:ID`
|**Referenced contract identifier** +
Identification of the referenced contract.

|`cbc:IssueDate`
|**Referenced contract issue date** +
Date of issue of the referenced contract, date should be formatted yyyy-mm-dd.

|`puf:BuyerContractID`
|**Referenced buyer contract identifier** +
ID for the buyer referenced contract document.

|`puf:BuyerContractIssueDate`
|**Referenced buyer contract issue date** +
Issue date for the buyer referenced contract document, date should be formatted yyyy-mm-dd.

|===

*Example* +
_Contract document ID and date_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI>
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension>
                          <puf:ContractDocumentReference>
                              <cbc:ID>123456</cbc:ID>
                              <cbc:IssueDate>2018-01-01</cbc:IssueDate>
                              <puf:BuyerContractID>BuyerContractID</puf:BuyerContractID>
                  						<puf:BuyerContractIssueDate>2019-01-01</puf:BuyerContractIssueDate>
                          </puf:ContractDocumentReference>
                      </puf:LineExtension>
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
