RestrictedInformation has been added on line level in order to cater the need for unique country specific data and internal customer information that might be required for internal processing. +

WARNING: Note that no customer specific information can be added without prior consulting with Pagero. If country specific information is available as restricted information value, this can be found in the Country Specific section.

The UBL extension to be used for TaxCurrencyLineExtensionAmount on line level is <<line-extension>>. +
The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/LineExtension`.

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:LineExtension>
                        <puf:RestrictedInformation/> <!--2-->
                    </puf:LineExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table show the definition of the new element added to the extension.

.Elements added in puf:RestrictedInformation
|===
|Element |Description

|`puf:Key`
|Key defining the type of value
|`puf:Value`
|Value relevant to the assigned key
|===

*Example* +
_RestrictedInformation example from Hungary specific section_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:LineExtension>
                        <puf:RestrictedInformation>
                            <puf:Key>lineModificationReferenceLineOperation</puf:Key>
                            <puf:Value>CREATE</puf:Value>
                        </puf:RestrictedInformation>
                    </puf:LineExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
