Element `TaxCurrencyTaxInclusiveLineExtensionAmount` has been added in order to specify the lines total amount including taxes in tax currency. +

The UBL extension to be used for TaxInclusiveLineExtensionAmount on line level is <<line-extension>>. +
The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/LineExtension`.
See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI> <!--1-->
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension/> <!--2-->
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added to puf:LineExtension
|===
|Element |Description

|`puf:TaxCurrencyTaxInclusiveLineExtensionAmount`
|Total line amount, including tax, discount and charges in tax currency.
|`puf:TaxCurrencyTaxInclusiveLineExtensionAmount/@currencyID`
|Currency of the TaxCurrencyTaxInclusiveLineExtensionAmount. +
For valid values see code list <<_puf_004_currencycode>>
|===

*Example* +
_Line with the total amount including tax both in document and tax currency_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI>
              <ext:ExtensionContent>
                  <puf:PageroExtension>
                      <puf:LineExtension>
                          <puf:TaxInclusiveLineExtensionAmount currencyID="EUR">100.00</puf:TaxInclusiveLineExtensionAmount> <!--1-->
                          <puf:TaxCurrencyTaxInclusiveLineExtensionAmount currencyID="USD">120.00</puf:TaxCurrencyTaxInclusiveLineExtensionAmount> <!--2-->
                      </puf:LineExtension>
                  </puf:PageroExtension>
              </ext:ExtensionContent>
          </ext:UBLExtension>
      </ext:UBLExtensions>
      <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> The amount including tax in document currency
<2> The amount including tax in tax currency
