Below table show available fields in `cac:AccountingSupplierParty`, note that additional elements has also been added to the extension available in <<_party>>.

.Additional elements added within cac:AccountingSupplierParty
|===
|Path |Description

|`cbc:CustomerAssignedAccountID`
|**Customer Account ID** +
Supplier ID, assigned by the buyer.

|`cac:Party/ext:UBLExtensions`
|**Extension Content** +
Extension is added to provide additional information in the `cac:Party` element, the information available can be found <<_party, here>>.

|`cac:Party/cbc:EndpointID`
|**Electronic Identifier** +
Seller's electronic address. +

|`cac:Party/cbc:EndpointID/@schemeID`
|**Electronic Identifier scheme ID** +
Scheme identifier of electronic address. +
Value must be according to code list https://pagero.github.io/puf-code-lists/#_puf_007_endpointscheme[PUF-007-ENDPOINTSCHEME^].

|`cac:Party/cac:PartyIdentification/cbc:ID`
|**Seller Identifier** +
Identifier of the seller.

|`cac:Party/cac:PartyIdentification/cbc:ID/@schemeID`
|**Seller Identifier** +
Scheme identifier of seller identifier. +
Value must be according to code list https://pagero.github.io/puf-code-lists/#_puf_008_identificationscheme[PUF-008-IDENTIFICATIONSCHEME^].

|`cac:Party/cac:PartyName/cbc:Name`
|**Seller name** +
Seller name.

|`cac:Party/cac:PostalAddress/cbc:ID`
|**Address ID** +
Seller's postal address id. +
Address identifier. Might be given by the authorities as standard numerical equivalent corresponding to neighborhood, plaza, streets etc.

|`cac:Party/cac:PostalAddress/cbc:Postbox`
|**Postal box** +
Seller's postal address post box.

|`cac:Party/cac:PostalAddress/cbc:Floor`
|**Floor** +
Seller's postal address floor. +
An addressable floor of a building.

|`cac:Party/cac:PostalAddress/cbc:Room`
|**Room** +
Seller's postal address room. +
A room, suite, or apartment of a building.

|`cac:Party/cac:PostalAddress/cbc:StreetName`
|**Street name** +
Seller's postal address street name.

|`cac:Party/cac:PostalAddress/cbc:AdditionalStreetName`
|**Additional Street name** +
Seller's postal address additional street name.

|`cac:Party/cac:PostalAddress/cbc:BuildingName`
|**Building name** +
Seller's postal address building name.

|`cac:Party/cac:PostalAddress/cbc:BuildingNumber`
|**Building number** +
Seller's postal address building number.

|`cac:Party/cac:PostalAddress/cbc:Department`
|**Department** +
Seller's postal address department.

|`cac:Party/cac:PostalAddress/cbc:PlotIdentification`
|**Plot Identification** +
Seller's postal address plot identification. +
Additional address number. An identifier for the piece of land associated with this address.

|`cac:Party/cac:PostalAddress/cbc:CitySubdivisionName`
|**City Subdvision Name** +
Seller's postal address city subdivision name. +
The name of the subdivision of the Seller city, town, or village in which its address is located, such as the name of its district or borough.

|`cac:Party/cac:PostalAddress/cbc:CityName`
|**City name** +
Seller's postal address city name.

|`cac:Party/cac:PostalAddress/cbc:PostalZone`
|**Postal zone** +
Seller's postal address post code.

|`cac:Party/cac:PostalAddress/cbc:CountrySubentity`
|**Country subentity** +
Seller's postal address province or state.

|`cac:Party/cac:PostalAddress/cbc:CountrySubentityCode`
|**Country subentity code** +
Seller's postal address province or state code.

|`cac:Party/cac:PostalAddress/cbc:Region`
|**Region** +
Seller's postal address region. +
Seller's addressable region or group of countries.

|`cac:Party/cac:PostalAddress/cbc:District`
|**District** +
Seller's postal address district. +
A district or borough, may be a subdivision of a city for this address.

|`cac:Party/cac:PostalAddress/cac:AddressLine/cbc:Line`
|**Additional address line** +
Note that `cbc:StreetName` and `cbc:AdditionalStreetName` should be populated prior of using this element.

|`cac:Party/cac:PostalAddress/cac:Country/cbc:IdentificationCode`
|**Country code** +
Seller's postal address country code.

|`cac:Party/cac:PostalAddress/cac:Country/cbc:Name`
|**Country name** +
Seller's postal address country name.

|`cac:Party/cac:PartyTaxScheme/cbc:CompanyID`
|**Company identifier** +
Seller's tax registration number.

|`cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:ID`
|**Tax scheme identifier** +
Seller's tax registration number tax scheme Identifier. +
_If `cac:PartyTaxScheme/cbc:CompanyID` is to be intepreted as a VAT registration text for Sweden and Norway e.g. "Godkänd för F-Skatt" or "Foretaksregisteret", `cac:TaxScheme/cbc:ID` must be "TAX"._

|`cac:Party/cac:PartyLegalEntity/cbc:RegistrationName`
|**Registration name** +
Seller's formal name or company name.

|`cac:Party/cac:PartyLegalEntity/cbc:CompanyID`
|**Legal company identifier** +
Seller's legal registration identifier.

|`cac:Party/cac:PartyLegalEntity/cbc:CompanyID/@schemeID`
|**Legal company scheme identifier** +
Seller's legal registration identifier scheme identifier +
Value must be according to code list https://pagero.github.io/puf-code-lists/#_puf_008_identificationscheme[PUF-008-IDENTIFICATIONSCHEME^].

|`cac:Party/cac:PartyLegalEntity/cbc:CompanyLegalForm`
|**Company legal form** +
Relevant legal information regarding the seller.

|`cac:Party/cac:Contact/cbc:Name`
|**Contact name** +
Name of contact person.

|`cac:Party/cac:Contact/cbc:Telephone`
|**Contact telephone** +
Phone number of contact person.

|`cac:Party/cac:Contact/cbc:ElectronicMail`
|**Contact E-mail** +
E-mail of contact person.

|`cac:Party/cac:Person/cbc:FirstName`
|**Person first name** +
First name of person. Should only be used if seller is a private individual.

|`cac:Party/cac:Person/cbc:FamilyName`
|**Person surname** +
Surname of person. Should only be used if seller is a private individual.

|`cac:AccountingContact/cbc:Telephone`
|**Accounting telephone** +
The telephone number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:Telefax`
|**Accounting fax number** +
The telefax number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:ElectronicMail`
|**Accounting E-mail** +
The e-mail address for the accounting contact of the organization.

|===

*Example* +
_cac:AccountingSupplierParty example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:AccountingSupplierParty>
      <cbc:CustomerAssignedAccountID>SupplierId</cbc:CustomerAssignedAccountID>
      <cac:Party>
          <cbc:EndpointID schemeID="0088">7300010000001</cbc:EndpointID>
          <cac:PartyIdentification>
              <cbc:ID schemeID="0088">7300010000001</cbc:ID>
          </cac:PartyIdentification>
          <cac:PartyName>
              <cbc:Name>Supplier Name</cbc:Name>
          </cac:PartyName>
          <cac:PostalAddress>
              <cbc:Postbox>12345</cbc:Postbox>
              <cbc:StreetName>Test Street 1</cbc:StreetName>
              <cbc:Department>Department</cbc:Department>
              <cbc:PlotIdentification>0000</cbc:PlotIdentification>
              <cbc:CitySubdivisionName>City Subdivision Name</cbc:CitySubdivisionName>
              <cbc:CityName>Town</cbc:CityName>
              <cbc:PostalZone>00000</cbc:PostalZone>
              <cbc:CountrySubentity>Province</cbc:CountrySubentity>
              <cac:Country>
                  <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                  <cbc:Name>Sweden</cbc:Name>
              </cac:Country>
          </cac:PostalAddress>
          <cac:PartyTaxScheme>
              <cbc:CompanyID>SE123456123401</cbc:CompanyID>
              <cac:TaxScheme>
                  <cbc:ID>VAT</cbc:ID>
              </cac:TaxScheme>
          </cac:PartyTaxScheme>
          <cac:PartyLegalEntity>
              <cbc:RegistrationName>Supplier Registration Name</cbc:RegistrationName>
              <cbc:CompanyID schemeID="0007">1234561234</cbc:CompanyID>
              <cac:RegistrationAddress>
                  <cbc:CityName>Supplier Hometown</cbc:CityName>
                  <cac:Country>
                      <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                  </cac:Country>
              </cac:RegistrationAddress>
          </cac:PartyLegalEntity>
          <cac:Contact>
              <cbc:Name>Supplier Contact Name</cbc:Name>
              <cbc:Telephone>11111111</cbc:Telephone>
              <cbc:ElectronicMail>supplier@contact.com</cbc:ElectronicMail>
          </cac:Contact>
      </cac:Party>
      <cac:AccountingContact>
          <cbc:Telephone>Supplier tel</cbc:Telephone>
          <cbc:Telefax>Supplier Fax</cbc:Telefax>
          <cbc:ElectronicMail>Supplier@mainContact.com</cbc:ElectronicMail>
      </cac:AccountingContact>
  </cac:AccountingSupplierParty>
  <!-- Code omitted for clarity -->
</Invoice>
----
