Below table show available fields in `cac:AccountingSupplierParty`. For common `cac:Party` elements, refer to <<_party>>.

.Additional elements added within cac:AccountingSupplierParty
|===
|Path |Description

|`cbc:CustomerAssignedAccountID`
|**Customer Account ID** +
Supplier ID, assigned by the buyer.

|`cac:Party`
|**Party** +
See <<_party>> for all available elements within `cac:Party`.

|`cac:Party/cac:AgentParty`
|**AgentParty** +
A party who acts as an agent for this party. +
For all available elements, refer to <<_party>>. +
**Note:** `cac:AgentParty` directly contains party elements (e.g., `cac:PostalAddress`, `cac:PartyLegalEntity`) without an intermediate `cac:Party` sub-element.

|`cac:Party/cac:ServiceProviderParty`
|**ServiceProviderParty** +
A party providing services for this party. +
Contains a nested `cac:Party` element. For all available elements within the nested party, refer to <<_party>>.

|`cac:AccountingContact/cbc:Name`
|**Accounting name** +
The name of the individual who serves as the accounting contact for the organization.

|`cac:AccountingContact/cbc:Telephone`
|**Accounting telephone** +
The telephone number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:Telefax`
|**Accounting fax number** +
The telefax number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:ElectronicMail`
|**Accounting E-mail** +
The e-mail address for the accounting contact of the organization.

|===

*Example* +
_cac:AccountingSupplierParty example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:AccountingSupplierParty>
      <cbc:CustomerAssignedAccountID>SupplierId</cbc:CustomerAssignedAccountID>
      <cac:Party>
          <cbc:WebsiteURI>www.pagero.com</cbc:WebsiteURI>
          <cbc:EndpointID schemeID="0088">7300010000001</cbc:EndpointID>
          <cac:PartyIdentification>
              <cbc:ID schemeID="0088">7300010000001</cbc:ID>
          </cac:PartyIdentification>
          <cac:PartyName>
              <cbc:Name>Supplier Name</cbc:Name>
          </cac:PartyName>
          <cac:PostalAddress>
              <cbc:Postbox>12345</cbc:Postbox>
              <cbc:StreetName>Test Street 1</cbc:StreetName>
              <cbc:Department>Department</cbc:Department>
              <cbc:PlotIdentification>0000</cbc:PlotIdentification>
              <cbc:CitySubdivisionName>City Subdivision Name</cbc:CitySubdivisionName>
              <cbc:CityName>Town</cbc:CityName>
              <cbc:PostalZone>00000</cbc:PostalZone>
              <cbc:CountrySubentity>Province</cbc:CountrySubentity>
              <cac:Country>
                  <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                  <cbc:Name>Sweden</cbc:Name>
              </cac:Country>
          </cac:PostalAddress>
          <cac:PartyTaxScheme>
              <cbc:CompanyID>SE123456123401</cbc:CompanyID>
              <cac:TaxScheme>
                  <cbc:ID>VAT</cbc:ID>
              </cac:TaxScheme>
          </cac:PartyTaxScheme>
          <cac:PartyLegalEntity>
              <cbc:RegistrationName>Supplier Registration Name</cbc:RegistrationName>
              <cbc:CompanyID schemeID="0007">1234561234</cbc:CompanyID>
              <cac:RegistrationAddress>
                  <cbc:CityName>Supplier Hometown</cbc:CityName>
                  <cac:Country>
                      <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                  </cac:Country>
              </cac:RegistrationAddress>
          </cac:PartyLegalEntity>
          <cac:Contact>
              <cbc:Name>Supplier Contact Name</cbc:Name>
              <cbc:Telephone>11111111</cbc:Telephone>
              <cbc:ElectronicMail>supplier@contact.com</cbc:ElectronicMail>
          </cac:Contact>
      </cac:Party>
      <cac:AccountingContact>
          <cbc:Name>Supplier Accounting Name</cbc:Name>
          <cbc:Telephone>Supplier Tel</cbc:Telephone>
          <cbc:Telefax>Supplier Fax</cbc:Telefax>
          <cbc:ElectronicMail>Supplier@mainContact.com</cbc:ElectronicMail>
      </cac:AccountingContact>
  </cac:AccountingSupplierParty>
  <!-- Code omitted for clarity -->
</Invoice>
----
