Below table show available fields in `cac:AccountingCustomerParty`. For common `cac:Party` elements, refer to <<_party>>.

.Additional elements added within cac:AccountingCustomerParty
|===
|Path |Description

|`cbc:SupplierAssignedAccountID`
|**Customer Account ID** +
Customer ID, assigned by the seller.

|`cac:Party`
|**Party** +
See <<_party>> for all available elements within `cac:Party`.

|===


.Additional party elements within cac:AccountingCustomerParty/cac:Party
|===
|Path |Description

|`cac:Party/cac:AgentParty`
|**AgentParty** +
A party who acts as an agent for this party. +
For all available elements, refer to <<_party>>. +
**Note:** `cac:AgentParty` directly contains party elements (e.g., `cac:PostalAddress`, `cac:PartyLegalEntity`) without an intermediate `cac:Party` sub-element.

|`cac:Party/cac:ServiceProviderParty`
|**ServiceProviderParty** +
A party providing services for this party. +
Contains a nested `cac:Party` element. For all available elements within the nested party, refer to <<_party>>.

|`cac:AccountingContact/cbc:Name`
|**Accounting name** +
The name of the individual who serves as the accounting contact for the organization.

|`cac:AccountingContact/cbc:Telephone`
|**Accounting telephone** +
The telephone number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:Telefax`
|**Accounting fax number** +
The telefax number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:ElectronicMail`
|**Accounting E-mail** +
The e-mail address for the accounting contact of the organization. +
 _(Also used for distribution via email through Pagero Online)._

|===

*Example* +
_cac:AccountingCustomerParty example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:AccountingCustomerParty>
      <cbc:SupplierAssignedAccountID>Customer Number</cbc:SupplierAssignedAccountID>
      <cac:Party>
          <cbc:EndpointID schemeID="0088">7300010000001</cbc:EndpointID>
          <cac:PartyIdentification>
              <cbc:ID schemeID="0088">7300010000001</cbc:ID>
          </cac:PartyIdentification>
          <cac:PartyName>
              <cbc:Name>Customer Name</cbc:Name>
          </cac:PartyName>
          <cac:PostalAddress>
              <cbc:Postbox>54321</cbc:Postbox>
              <cbc:StreetName>Customer Street</cbc:StreetName>
              <cbc:Department>Customer Department</cbc:Department>
              <cbc:PlotIdentification>0000</cbc:PlotIdentification>
              <cbc:CitySubdivisionName>Customer City Subdivision Name</cbc:CitySubdivisionName>
              <cbc:CityName>Customer City</cbc:CityName>
              <cbc:PostalZone>00000</cbc:PostalZone>
              <cbc:CountrySubentity>Customer Province</cbc:CountrySubentity>
              <cac:Country>
                  <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                  <cbc:Name>Sweden</cbc:Name>
              </cac:Country>
          </cac:PostalAddress>
          <cac:PartyTaxScheme>
              <cbc:CompanyID>SE987654321001</cbc:CompanyID>
              <cac:TaxScheme>
                  <cbc:ID>VAT</cbc:ID>
              </cac:TaxScheme>
          </cac:PartyTaxScheme>
          <cac:PartyLegalEntity>
              <cbc:RegistrationName>Customer Registration Name</cbc:RegistrationName>
              <cbc:CompanyID schemeID="0007">987654-4321</cbc:CompanyID>
          </cac:PartyLegalEntity>
          <cac:Contact>
              <cbc:Name>Customer Contact Name</cbc:Name>
              <cbc:Telephone>+465544466</cbc:Telephone>
              <cbc:ElectronicMail>customer@contact.com</cbc:ElectronicMail>
          </cac:Contact>
      </cac:Party>
      <cac:AccountingContact>
          <cbc:Name>Customer Accounting Name</cbc:Name>
          <cbc:Telephone>Customer Tel</cbc:Telephone>
          <cbc:Telefax>Customer Fax</cbc:Telefax>
          <cbc:ElectronicMail>Customer@mainContact.com</cbc:ElectronicMail>
      </cac:AccountingContact>
  </cac:AccountingCustomerParty>
  <!-- Code omitted for clarity -->
</Invoice>
----
