Below table show available fields in `cac:BillingReference/cac:InvoiceDocumentReference`, note that additional elements has also been added to the extension available in <<_billingreference>>.

.Elements added in cac:BillingReference/cac:InvoiceDocumentReference
|===
|Path |Description

|`ext:UBLExtensions`
|**Extension Content** +
Extension is added to provide additional information in the `cac:BillingReference/cac:InvoiceDocumentReference` element, the information available can be found <<_billingreference, here>>.

|`cbc:ID`
|**Preceding invoice number** +
Identifier of a previous issued invoice.

|`cbc:UUID`
|**Preceding invoice UUID** +
The UUID assigned to the referenced invoice, separate from its invoice number in `cbc:ID` and from the UUID of the current document. +
Provide the value directly in this element. No PUF extension is required.

|`cbc:IssueDate`
|**Issue date** +
Issue date of previous issued invoice. +
_Format "YYYY-MM-DD"._

|`cbc:DocumentTypeCode`
|**Referenced document type code** +
A code that specifies the type of document being referenced, such as an invoice, credit note, or other document type.

|===

*Example* +
_cbc:Note example_
[source,xml]
----
<Invoice>
    <!-- Code omitted for clarity -->
    <cac:BillingReference>
        <cac:InvoiceDocumentReference>
            <cbc:ID>1144884</cbc:ID>
            <cbc:UUID>00000000-0000-5000-8000-000000000011</cbc:UUID>
            <cbc:IssueDate>2021-01-01</cbc:IssueDate>
            <cbc:DocumentTypeCode>380</cbc:DocumentTypeCode>
        </cac:InvoiceDocumentReference>
    </cac:BillingReference>
    <!-- Code omitted for clarity -->
</Invoice>
----
