In PUF, a new party has been added called Buyer Customer Party. This party should contain information regarding the buyer of the goods or service and should *ONLY* be used if the buyer party differs from accounting customer party.

If `cac:BuyerCustomerParty` is used, the `cac:AccountingCustomerParty` is to be considered the receiver of the document.

Below table show available fields in `cac:BuyerCustomerParty`. For common `cac:Party` elements, refer to <<_party>>.

.Elements added in cac:BuyerCustomerParty
|===
|Path |Description

|`cbc:SupplierAssignedAccountID`
|**Customer Account ID** +
Customer ID, assigned by the seller.

|`cac:Party`
|**Party** +
See <<_party>> for all available elements within `cac:Party`.

|`cac:AccountingContact/cbc:Name`
|**Accounting name** +
The name of the individual who serves as the accounting contact for the organization.

|`cac:AccountingContact/cbc:Telephone`
|**Accounting telephone** +
The telephone number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:Telefax`
|**Accounting fax number** +
The telefax number for the accounting contact of the organization.

|`cac:AccountingContact/cbc:ElectronicMail`
|**Accounting E-mail** +
The e-mail address for the accounting contact of the organization.

|===

*Example* +
_Party structure with both invoice recipient party and buyer party_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:AccountingCustomerParty> <!--1-->
      <cac:Party>
          <cbc:EndpointID schemeID="0088">1234567890123</cbc:EndpointID>
          <cac:PartyIdentification>
              <cbc:ID schemeID="0007">1234561234</cbc:ID>
          </cac:PartyIdentification>
          <cac:PartyName>
              <cbc:Name>Receiver Trading Name AB</cbc:Name>
          </cac:PartyName>
          <cac:PostalAddress>
              <cbc:StreetName>Street 32</cbc:StreetName>
              <cbc:AdditionalStreetName>Po box 878</cbc:AdditionalStreetName>
              <cbc:PlotIdentification>0000</cbc:PlotIdentification>
              <cbc:CitySubdivisionName>City Subdivision Name</cbc:CitySubdivisionName>
              <cbc:CityName>Stockholm</cbc:CityName>
              <cbc:PostalZone>123 12</cbc:PostalZone>
              <cac:Country>
                  <cbc:IdentificationCode>SE</cbc:IdentificationCode>
              </cac:Country>
          </cac:PostalAddress>
          <cac:PartyTaxScheme>
              <cbc:CompanyID>SE123456789001</cbc:CompanyID>
              <cac:TaxScheme>
                  <cbc:ID>VAT</cbc:ID>
              </cac:TaxScheme>
          </cac:PartyTaxScheme>
          <cac:PartyLegalEntity>
              <cbc:RegistrationName>Receiver legal Name</cbc:RegistrationName>
              <cbc:CompanyID schemeID="0007">1234561234</cbc:CompanyID>
          </cac:PartyLegalEntity>
          <cac:Contact>
              <cbc:Name>Anders Andersson</cbc:Name>
              <cbc:Telephone>555444666</cbc:Telephone>
              <cbc:ElectronicMail>contact@receiver.com</cbc:ElectronicMail>
          </cac:Contact>
      </cac:Party>
  </cac:AccountingCustomerParty>
  <cac:BuyerCustomerParty> <!--2-->
      <cac:Party>
          <cbc:EndpointID schemeID="0088">7322010000001</cbc:EndpointID>
          <cac:PartyIdentification>
              <cbc:ID schemeID="0007">1111112222</cbc:ID>
          </cac:PartyIdentification>
          <cac:PartyName>
              <cbc:Name>Buyer Trading Name AB</cbc:Name>
          </cac:PartyName>
          <cac:PostalAddress>
              <cbc:StreetName>Street 32</cbc:StreetName>
              <cbc:AdditionalStreetName>Po box 878</cbc:AdditionalStreetName>
              <cbc:PlotIdentification>0000<cbc:PlotIdentification>
              <cbc:CitySubdivisionName>City Subdivision Name</cbc:CitySubdivisionName>
              <cbc:CityName>Stockholm</cbc:CityName>
              <cbc:PostalZone>123 12</cbc:PostalZone>
              <cac:Country>
                  <cbc:IdentificationCode>SE</cbc:IdentificationCode>
              </cac:Country>
          </cac:PostalAddress>
          <cac:PartyTaxScheme>
              <cbc:CompanyID>SE111111222201</cbc:CompanyID>
              <cac:TaxScheme>
                  <cbc:ID>VAT</cbc:ID>
              </cac:TaxScheme>
          </cac:PartyTaxScheme>
          <cac:PartyLegalEntity>
              <cbc:RegistrationName>Buyer legal Name</cbc:RegistrationName>
              <cbc:CompanyID schemeID="0007">1111112222</cbc:CompanyID>
          </cac:PartyLegalEntity>
          <cac:Contact>
              <cbc:Name>Daniel Danielsson</cbc:Name>
              <cbc:Telephone>33322221111</cbc:Telephone>
              <cbc:ElectronicMail>contact@buyer.com</cbc:ElectronicMail>
          </cac:Contact>
      </cac:Party>
  </cac:BuyerCustomerParty>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> Information in `cac:AccountingCustomerParty` will be used to identify the _receiver_ of the document.
<2> Information in `cac:BuyerCustomerParty` will be sent to the receiver as _buyer_ information.

WARNING: Please note that NOT all e-invoice formats support both invoice recipient and buyer party information, therefore only use both structures when needed.
