Below table show available fields in `cac:Delivery`, note that additional elements has also been added to the extension available in <<_delivery, cac:Delivery>> and <<_party, cac:Delivery/cac:DeliveryParty>>.

.Elements added in cac:Delivery
|===
|Path |Description

|`ext:UBLExtensions`
|**Extension Content** +
Extension is added to provide additional information in the `cac:Delivery` element, the information available can be found <<_delivery, here>>.

|`cbc:ActualDeliveryDate`
|**Delivery date** +
Date when goods or service was made or completed. +
_Format YYYY-MM-DD._

|`cbc:LatestDeliveryDate`
|**Latest delivery date** +
The latest date of delivery allowed by the buyer. +
_Format YYYY-MM-DD._

|`cac:DeliveryLocation/cbc:ID`
|**Delivery location identifier** +
Identifier of the delivery location. +
_E.g. GLN number._

|`cac:DeliveryLocation/cbc:ID/@schemeID`
|**Delivery location identifier scheme identifier** +
Scheme identifier of the delivery location identifier. +
_E.g. 0088._ +
Value must be according to code list https://pagero.github.io/puf-code-lists/#_puf_008_identificationscheme[PUF-008-IDENTIFICATIONSCHEME^].

|`cac:DeliveryLocation/cbc:Description`
|**Delivery location description** +
Description of the delivery location.

|`cac:DeliveryLocation/cac:Address/cbc:ID`
|**Address ID** +
Delivery location address id. +
Address identifier. Might be given by the authorities as standard numerical equivalent corresponding to neighborhood, plaza, streets etc.

|`cac:DeliveryLocation/cac:Address/cbc:Postbox`
|**Postal box** +
Delivery location address post box.

|`cac:DeliveryLocation/cac:Address/cbc:Floor`
|**Floor** +
Delivery location address floor. +
An addressable floor of a building.

|`cac:DeliveryLocation/cac:Address/cbc:Room`
|**Room** +
Delivery location address room. +
A room, suite, or apartment of a building.

|`cac:DeliveryLocation/cac:Address/cbc:StreetName`
|**Street name** +
Delivery location address street name.

|`cac:DeliveryLocation/cac:Address/cbc:AdditionalStreetName`
|**Additional Street name** +
Delivery location address additional street name.

|`cac:DeliveryLocation/cac:Address/cbc:BuildingName`
|**Building name** +
Delivery location address building name.

|`cac:DeliveryLocation/cac:Address/cbc:BuildingNumber`
|**Building number** +
Delivery location address building number.

|`cac:DeliveryLocation/cac:Address/cbc:Department`
|**Department** +
Delivery location address department.

|`cac:DeliveryLocation/cac:Address/cbc:PlotIdentification`
|**Plot Identification** +
Delivery location address plot identification. +
Additional address number. An identifier for the piece of land associated with this address.

|`cac:DeliveryLocation/cac:Address/cbc:CitySubdivisionName`
|**City Subdvision Name** +
Delivery location address city subdivision name. +
The name of the subdivision of the delivery city, town, or village in which its address is located, such as the name of its district or borough.

|`cac:DeliveryLocation/cac:Address/cbc:CityName`
|**City name** +
Delivery location address city name.

|`cac:DeliveryLocation/cac:Address/cbc:PostalZone`
|**Postal zone** +
Delivery location address post code.

|`cac:DeliveryLocation/cac:Address/cbc:CountrySubentity`
|**Country subentity** +
Delivery location address province or state.

|`cac:DeliveryLocation/cac:Address/cbc:CountrySubentityCode`
|**Country subentity code** +
Delivery location address province or state code.

|`cac:DeliveryLocation/cac:Address/cbc:Region`
|**Region** +
Delivery location address region. +
Delivery location addressable region or group of countries.

|`cac:DeliveryLocation/cac:Address/cbc:District`
|**District** +
Delivery location address district. +
A district or borough, may be a subdivision of a city for this address.

|`cac:DeliveryLocation/cac:Address/cac:AddressLine/cbc:Line`
|**Additional address line** +
Note that `cbc:StreetName` and `cbc:AdditionalStreetName` should be populated prior of using this element.

|`cac:DeliveryLocation/cac:Address/cac:Country/cbc:IdentificationCode`
|**Country code** +
Delivery location address country code.

|`cac:DeliveryLocation/cac:Address/cac:Country/cbc:Name`
|**Country name** +
Delivery location address country name.

|`cac:DeliveryParty/ext:UBLExtensions`
|**Extension Content** +
Extension is added to provide additional information in the `cac:Party` element, the information available can be found <<_party, here>>.

|`cac:DeliveryParty/cac:PartyIdentification/cbc:ID`
|**Party Identifier** +
Identifier of the delivery party.

|`cac:DeliveryParty/cac:PartyIdentification/cbc:ID/@schemeID`
|**Party Identifier** +
Scheme identifier of delivery party identifier +
Value must be according to code list https://pagero.github.io/puf-code-lists/#_puf_008_identificationscheme[PUF-008-IDENTIFICATIONSCHEME^].

|`cac:DeliveryParty/cac:PartyName/cbc:Name`
|**Delivery party name** +
Name of the party that the goods/services is sent to.

|`cac:DeliveryParty/cac:Contact/cbc:Name`
|**Delivery party contact name** +
Name of the contact to which the goods/services is sent to.

|`cac:DeliveryParty/cac:Contact/cbc:Telephone`
|**Delivery party contact telephone** +
Telephone of the contact to which the goods/services is sent to.

|`cac:DeliveryParty/cac:Contact/cbc:ElectronicMail`
|**Delivery party contact email** +
Email of the contact to which the goods/services is sent to.

|`cac:Despatch/cac:DespatchParty/cac:PartyName/cbc:Name`
|**Despatch party name** +
Name of the party responsible for the despatch.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:ID`
|**Address ID** +
Despatch party postal address id. +
Address identifier. Might be given by the authorities as standard numerical equivalent corresponding to neighborhood, plaza, streets etc.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:Postbox`
|**Postal box** +
Despatch party postal address post box.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:Floor`
|**Floor** +
Despatch party postal address floor. +
An addressable floor of a building.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:Room`
|**Room** +
Despatch party postal address room. +
A room, suite, or apartment of a building.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:StreetName`
|**Street name** +
Despatch party postal address street name.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:AdditionalStreetName`
|**Additional Street name** +
Despatch party postal address additional street name.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:BuildingName`
|**Building name** +
Despatch party postal address building name.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:BuildingNumber`
|**Building number** +
Despatch party postal address building number.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:Department`
|**Department** +
Despatch party postal address department.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:PlotIdentification`
|**Plot Identification** +
Despatch party postal address plot identification. +
Additional address number. An identifier for the piece of land associated with this address.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:CitySubdivisionName`
|**City Subdvision Name** +
Despatch party postal address city subdivision name. +
The name of the subdivision of the city, town, or village in which the address is located, such as the name of its district or borough.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:CityName`
|**City name** +
Despatch party postal address city name.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:PostalZone`
|**Postal zone** +
Despatch party postal address post code.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:CountrySubentity`
|**Country subentity** +
Despatch party postal address province or state.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:CountrySubentityCode`
|**Country subentity code** +
Despatch party postal address province or state code.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:Region`
|**Region** +
Despatch party postal address region. +
Despatch party addressable region or group of countries.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cbc:District`
|**District** +
Despatch party postal address district. +
A district or borough, may be a subdivision of a city for this address.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cac:AddressLine/cbc:Line`
|**Additional address line** +
Note that `cbc:StreetName` and `cbc:AdditionalStreetName` should be populated prior of using this element.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cac:Country/cbc:IdentificationCode`
|**Country code** +
Despatch party postal address country code.

|`cac:Despatch/cac:DespatchParty/cac:PostalAddress/cac:Country/cbc:Name`
|**Country name** +
Despatch party postal address country name.

|===

*Example* +
_cac:Delivery populated with example value_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:Delivery>
      <cbc:ActualDeliveryDate>2019-01-01</cbc:ActualDeliveryDate>
      <cbc:LatestDeliveryDate>2019-01-03</cbc:LatestDeliveryDate>
      <cac:DeliveryLocation>
          <cbc:ID schemeID="0088">7300010000001</cbc:ID>
          <cbc:Description>Text describing the delivery location</cbc:Description>
          <cac:Address>
              <cbc:Postbox>121212</cbc:Postbox>
              <cbc:StreetName>Delivery Street</cbc:StreetName>
              <cbc:Department>Delivery Department</cbc:Department>
              <cbc:PlotIdentification>0000</cbc:PlotIdentification>
              <cbc:CitySubdivisionName>Delivery City Subdivision Name</cbc:CitySubdivisionName>
              <cbc:CityName>Delivery City</cbc:CityName>
              <cbc:PostalZone>55555</cbc:PostalZone>
              <cbc:CountrySubentity>Delivery Province</cbc:CountrySubentity>
              <cac:Country>
                  <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                  <cbc:Name>Sweden</cbc:Name>
              </cac:Country>
          </cac:Address>
      </cac:DeliveryLocation>
      <cac:DeliveryParty>
          <cac:PartyName>
              <cbc:Name>Delivery Name</cbc:Name>
          </cac:PartyName>
          <cac:Contact>
              <cbc:Name>Anders Andersson</cbc:Name>
              <cbc:Telephone>01113354</cbc:Telephone>
              <cbc:ElectronicMail>DeliveryContact@mail.com</cbc:ElectronicMail>
          </cac:Contact>
      </cac:DeliveryParty>
      <cac:Despatch>
          <cac:DespatchParty>
              <cac:PartyName>
                  <cbc:Name>Despatch party name</cbc:Name>
              </cac:PartyName>
              <cac:PostalAddress>
                  <cbc:StreetName>Street 1</cbc:StreetName>
                  <cbc:CityName>Jammu</cbc:CityName>
                  <cbc:PostalZone>181131</cbc:PostalZone>
                  <cbc:CountrySubentityCode>01</cbc:CountrySubentityCode>
                  <cac:Country>
                      <cbc:IdentificationCode>IN</cbc:IdentificationCode>
                      <cbc:Name>India</cbc:Name>
                  </cac:Country>
              </cac:PostalAddress>
          </cac:DespatchParty>
      </cac:Despatch>
  </cac:Delivery>
  <!-- Code omitted for clarity -->
</Invoice>
----
