Below table show available fields in cac:LegalMonetaryTotal, note that additional elements has also been added to the extension available in <<_legalmonetarytotal, cac:LegalMonetaryTotal>>.

.Elements added in cac:LegalMonetaryTotal
|===
|Element |Description

|`ext:UBLExtensions`
|**Extension Content** +
Extension is added to provide additional information in the `cac:LegalMonetaryTotal` element, the information available can be found <<_legalmonetarytotal, here>>.

|`cbc:LineExtensionAmount`
|**Summary of all lines net amount** +
Summary of all lines net amount. +
_Summary of all TaxSubTotal/TaxAmount._

|`cbc:LineExtensionAmount/@currencyID`
|**Summary of all lines net amount currency** +
Currency applied for `cbc:LineExtensionAmount`, must be the same as `cbc:DocumentCurrencyCode`. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cbc:TaxExclusiveAmount`
|**Total invoice amount excluding tax** +
Documents total invoice amount, excluding taxes. +

|`cbc:TaxExclusiveAmount/@currencyID`
|**Total invoice amount currency excluding tax** +
Currency applied for `cbc:TaxExclusiveAmount`, must be the same as `cbc:DocumentCurrencyCode`. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cbc:TaxInclusiveAmount`
|**Total invoice amount including tax** +
Documents total invoice amount, including taxes.

|`cbc:TaxInclusiveAmount/@currencyID`
|**Total invoice amount currency including tax** +
Currency applied for `cbc:TaxInclusiveAmount`, including taxes, must be the same as `cbc:DocumentCurrencyCode`. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cbc:AllowanceTotalAmount`
|**Summary of all allowances on document level** +
Total amount of all allowances on document level (`Invoice/cac:AllowanceCharge/cbc:Amount` where `cbc:ChargeIndicator` equals false).

|`cbc:AllowanceTotalAmount/@currencyID`
|**Summary of all allowances on document level currency** +
Currency applied for `cbc:AllowanceTotalAmount`, must be the same as `cbc:DocumentCurrencyCode`. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cbc:ChargeTotalAmount`
|**Summary of all charges on document level** +
Total amount of all charges on document level (`Invoice/cac:AllowanceCharge/cbc:Amount` where `cbc:ChargeIndicator` equals true).

|`cbc:ChargeTotalAmount/@currencyID`
|**Summary of all charges on document level currency** +
Currency applied for cbc:ChargeTotalAmount, must be the same as cbc:DocumentCurrencyCode. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cbc:PrepaidAmount`
|**Amount already prepaid** +
Amount that has already been paid and should be subtracted from the payable amount.

|`cbc:PrepaidAmount/@currencyID`
|**Prepaid amount currency** +
Currency applied for `cbc:PrepaidAmount`, must be the same as `cbc:DocumentCurrencyCode`. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cbc:PayableRoundingAmount`
|**Rounding amount** +
Rounding amount, should be applied to the calculation of payable amount.

|`cbc:PayableRoundingAmount/@currencyID`
|**Rounding amount currency** +
Currency applied for `cbc:PayableRoundingAmount`, must be the same as `cbc:DocumentCurrencyCode`. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cbc:PayableAmount`
|**Payable amount** +
Document total amount that should be paid, amount equals the subtraction of prepaid amount and including any rounding amount.

|`cbc:PayableAmount/@currencyID`
|**Payable amount currency** +
Currency applied for `cbc:PayableAmount`, must be the same as `cbc:DocumentCurrencyCode`. +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|===

*Example* +
_cac:LegalMonetaryTotal example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:LegalMonetaryTotal>
        <cbc:LineExtensionAmount currencyID="EUR">100.00</cbc:LineExtensionAmount>
        <cbc:TaxExclusiveAmount currencyID="EUR">95.00</cbc:TaxExclusiveAmount>
        <cbc:TaxInclusiveAmount currencyID="EUR">120.00</cbc:TaxInclusiveAmount>
        <cbc:AllowanceTotalAmount currencyID="EUR">5.00</cbc:AllowanceTotalAmount>
        <cbc:ChargeTotalAmount currencyID="EUR">0.00</cbc:ChargeTotalAmount>
        <cbc:PayableAmount currencyID="EUR">110.00</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>
  <!-- Code omitted for clarity -->
</Invoice>
----
