.Elements available in cac:PaymentMeans
|===
|Path |Description

|`cbc:PaymentMeansCode`
|**Payment means code** +
Code for how the payment is to be settled. +
_E.g. 30._ +
Value must be according to code list https://pagero.github.io/puf-code-lists/#_puf_010_paymentmeanscode[PUF-010-PAYMENTMEANSCODE^].

|`cbc:PaymentMeansCode/@name`
|**Payment means name** +
Name describing the payment means.

|`cbc:PaymentID`
|**Payment Identifier** +
Identifier for the payment. +
_E.g. OCR, KID etc._

|`cac:CardAccount/cbc:PrimaryAccountNumberID`
|**Primary account number identifier** +
The Primary Account Number (PAN) of the card used for payment. +
In accordance with card payments security standards, an invoice should never include a full card primary account number.

|`cac:CardAccount/cbc:NetworkID`
|**Card network** +
Name of card company.

|`cac:CardAccount/cbc:HolderName`
|**Card holder name** +
Name of the card holder.

|`cac:PayeeFinancialAccount/cbc:ID`
|**Payment account number** +
Account number e.g.IBAN och BBAN.

|`cac:PayeeFinancialAccount/cbc:Name`
|**Payment account name** +
The name of the payment account, at a payment service provider, to which payment should be made.

|`cac:PayeeFinancialAccount/cbc:CurrencyCode`
|**Payment account currency code** +
The currency in which the Financial Account is held expressed as a code. +
 _Value must be according to ISO 4217 Currency codes._ +
For valid values see code list https://pagero.github.io/puf-code-lists/#_puf_004_currencycode[PUF-004-CURRENCYCODE^].

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cbc:ID`
|**Payment account identifier ** +
Payment account identifier e.g. a BIC or Swift.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cbc:Name`
|**Payment bank name** +
The name of the bank branch or division of the bank organization, to which payment should be made.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:Postbox`
|**Postal box** +
Bank address post box.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:Floor`
|**Floor** +
Bank address floor. +
An addressable floor of a building.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:Room`
|**Room** +
Bank address room. +
A room, suite, or apartment of a building.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:StreetName`
|**Street name** +
Bank address street name.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:AdditionalStreetName`
|**Additional Street name** +
Bank address additional street name.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:BuildingName`
|**Building name** +
Bank address building name.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:BuildingNumber`
|**Building number** +
Bank address building number.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:Department`
|**Department** +
Bank address department.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:PlotIdentification`
|**Plot Identification** +
Bank address plot identification. +
Additional address number. An identifier for the piece of land associated with this address.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:CitySubdivisionName`
|**City Subdvision Name** +
Bank address city subdivision name. +
The name of the subdivision of the delivery city, town, or village in which its address is located, such as the name of its district or borough.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:CityName`
|**City name** +
Bank address city name.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:PostalZone`
|**Postal zone** +
Bank address post code.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:CountrySubentity`
|**Country subentity** +
Bank address province or state.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:CountrySubentityCode`
|**Country subentity code** +
Bank address province or state code.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:Region`
|**Region** +
Bank address region. +
Bank addressable region or group of countries.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cbc:District`
|**District** +
Bank address district. +
A district or borough, may be a subdivision of a city for this address.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cac:AddressLine/cbc:Line`
|**Additional address line** +
Note that `cbc:StreetName` and `cbc:AdditionalStreetName` should be populated prior of using this element.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cac:Country/cbc:IdentificationCode`
|**Country code** +
Bank address country code.

|`cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address/cac:Country/cbc:Name`
|**Country name** +
Bank address country name.

|`cac:PaymentMandate/cbc:ID`
|**Payment mandate reference identifier** +
Payment mandate identifier used for referencing direct debit payments.

|`cac:PaymentMandate/cac:PayerFinancialAccount/cbc:ID`
|**Payer account identifier** +
Account to be debited in a direct debit payment.

|===

*Example* +
_cbc:PaymentMeans example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:PaymentMeans>
    <cbc:PaymentMeansCode>30</cbc:PaymentMeansCode>
    <cbc:PaymentID>123456</cbc:PaymentID>
    <cac:PayeeFinancialAccount>
        <cbc:ID>12345678</cbc:ID>
        <cbc:Name>AccountName</cbc:Name>
        <cac:FinancialInstitutionBranch>
            <cbc:ID>SE:BANKGIRO</cbc:ID>
            <cbc:Name>BankName</cbc:Name>
            <cac:Address>
                    <cbc:Postbox>111</cbc:Postbox>
                    <cbc:StreetName>Bank Street</cbc:StreetName>
                    <cbc:BuildingNumber>11</cbc:BuildingNumber>
                    <cbc:Department>Bank Department</cbc:Department>
                    <cbc:PlotIdentification>0000</cbc:PlotIdentification>
                    <cbc:CitySubdivisionName>Bank City Subdivision Name</cbc:CitySubdivisionName>
                    <cbc:CityName>Bank City</cbc:CityName>
                    <cbc:PostalZone>22233</cbc:PostalZone>
                    <cbc:CountrySubentity>Bank Province</cbc:CountrySubentity>
                    <cac:Country>
                        <cbc:IdentificationCode>SE</cbc:IdentificationCode>
                        <cbc:Name>Sweden</cbc:Name>
                    </cac:Country>
                </cac:Address>
        </cac:FinancialInstitutionBranch>
    </cac:PayeeFinancialAccount>
  </cac:PaymentMeans>
  <!-- Code omitted for clarity -->
</Invoice>
----
