Below table lists all additional elements added to extend the `(Invoice|CreditNote)/cac:AccountingSupplierParty` and `(Invoice|CreditNote)/cac:AccountingCustomerParty`.

.Additional elements added within cac:AccountingSupplierParty and cac:AccountingCustomerParty
|===
|Applicable XPath |Description

|`cbc:SupplierAssignedAccountID`
|Customer number in the suppliers system (use only in cac:AccountingCustomerParty).
|`cbc:CustomerAssignedAccountID`
|Supplier number in the customers system (use only in cac:AccountingSupplierParty).
|`cac:Party/cac:PostalAddress/cbc:Postbox`
|The post box.
|`cac:Party/cac:PostalAddress/cbc:Department`
|The department of the addressee.
|`cac:Party/cac:PostalAddress/cac:Country/cbc:Name`
|The country name.
|`cac:AccountingContact/cbc:Telephone`
|The telephone number for the accounting contact of the organization.
|`cac:AccountingContact/cbc:Telefax`
|The telefax number for the accounting contact of the organization.
|`cac:AccountingContact/cbc:ElectronicMail`
|The e-mail address for the accounting contact of the organization.
|===

An extension has been created for providing additional information not supported in UBL 2.1.
The UBL extension to be used for below elements is `cac:Party/ext:UBLExtensions` and the structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/PartyExtension`. +

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<cac:Party>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:PartyExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:PartyExtension/> <!--2-->
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:Party>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added in puf:PartyExtension
|===
|Applicable XPath |Description

|`puf:RegistrationData/cbc:ID`
|Additional registration data associated with the party.
|`puf:RegistrationData/puf:IDType`
|To identify the type of registration data. The IDType must be coded using the <<_puf_001_registrationdata>> code list.
|`puf:RegistrationData/puf:IDType/@listID`
|Registration data IDType must have a list identifier attribute “PUF-001-REGISTRATIONDATA”.
|`puf:ADAID/cbc:ID`
|Additional destination address identifier.
|`puf:ADAID/cbc:Name`
|Name of the additional destination unit.
|`puf:ADAID/puf:IDType`
|To identify the type of additional destination address identifier. The IDType must be coded using the <<_puf_002_adaid>> code list.
|`puf:ADAID/puf:IDType/@listID`
|IDType must have a list identifier attribute “PUF-002-ADAID”.
|===

===== Registration data

When there is a need to provide additional registration data associated with the organization this can be done using the RegistrationData element.
To identify the type of registration data. The `puf:IDType` must be coded using the PUF-001-REGISTRATIONDATA code list. See code list <<_puf_001_registrationdata>> for all supported types of registration data.

*Example*

[source,xml]
----
<cac:Party>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:PartyExtension</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:PartyExtension>
                        <puf:RegistrationData>
                            <cbc:ID>SomeRegistrationData</cbc:ID>
                            <puf:IDType listID="PUF-001-REGISTRATIONDATA">ES:Folio</puf:IDType>
                        </puf:RegistrationData>
                        <puf:RegistrationData>
                            <cbc:ID>SomeRegistrationData</cbc:ID>
                            <puf:IDType listID="PUF-001-REGISTRATIONDATA">ES:Book</puf:IDType>
                        </puf:RegistrationData>
                    </puf:PartyExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:Party>
----

===== Additional Destination Address Identifier (ADAID)

Additional Destination Address Identifier (ADAID) is used when there is a need to provide additional routing codes in order for the invoice to be sent to the correct recipient.
This is mostly used to public entities (e.g. government recipients). To identify the type of ADAID, the `puf:IDType` must be coded using the PUF-002-ADAID code list. See code list <<_puf_002_adaid>> for supported types of ADAID.


*Example*

[source,xml]
----
<cac:Party>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:PartyExtension</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                  <puf:PartyExtension>
                      <puf:ADAID>
                          <cbc:ID>1234567890</cbc:ID>
                          <cbc:Name>Name of Unit</cbc:Name>
                          <puf:IDType listID="PUF-002-ADAID">FR:ServiceCode</puf:IDType>
                      </puf:ADAID>
                  </puf:PartyExtension>
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity -->
</cac:Party>
----
