In Pagero UF, a new party has been added called Buyer Customer Party. This party should contain information regarding the buyer of the goods or service and should only be used if the buyer party differs from accounting customer party.

If Buyer Customer Party is used, the Accounting Customer Party is to be considered the receiver of the document.

Below table lists all additional elements added within `(Invoice|CreditNote)/cac:BuyerCustomerParty`.

.Elements added in cac:BuyerCustomerParty
|===
|Applicable XPath |Description

|`cbc:SupplierAssignedAccountID`
|Customer ID in the suppliers system.
|`cac:Party/cac:PartyIdentification/cbc:ID`
|Identifier for the buyer.
|`cac:Party/cac:PartyIdentification/cbc:ID/@schemeID`
|Party Identifier Scheme MUST be coded using one of the ISO 6523 ICD list.
|`cac:Party/cac:PartyName/cbc:Name`
|The name of the buyer party.
|`cac:Party/cac:PostalAddress/cbc:Postbox`
|The buyers post box.
|`cac:Party/cac:PostalAddress/cbc:StreetName`
|The buyers street address.
|`cac:Party/cac:PostalAddress/cbc:AdditionalStreetName`
|The buyers additional street address.
|`cac:Party/cac:PostalAddress/cbc:Department`
|The buyers department.
|`cac:Party/cac:PostalAddress/cbc:CityName`
|City of the buyer.
|`cac:Party/cac:PostalAddress/cbc:PostalZone`
|The buyers postal zone.
|`cac:Party/cac:PostalAddress/cbc:CountrySubentity`
|Province of the buyer..
|`cac:Party/cac:PostalAddress/cac:Country/cbc:IdentificationCode`
|Country code of the buyer.
|`cac:Party/cac:PostalAddress/cac:Country/cbc:Name`
|The country name of the buyer
|`cac:Party/cac:PartyTaxScheme/cbc:CompanyID`
|Company ID of the buyer, type of ID defined by TaxScheme ID.
|`cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:ID`
|Type of ID e.g. VAT.
|`cac:Party/cac:PartyLegalEntity/cbc:RegistrationName`
|Buyers legal name.
|`cac:Party/cac:PartyLegalEntity/cbc:CompanyID`
|Buyers legal registration ID.
|`cac:Party/cac:PartyLegalEntity/cbc:CompanyID/@schemeID`
|Identifier of buyer legal registration ID.
|`cac:Party/cac:Contact/cbc:Name`
|Buyer contact name.
|`cac:Party/cac:Contact/cbc:Telephone`
|Buyer contact telephone number.
|`cac:Party/cac:Contact/cbc:ElectronicMail`
|Buyer contact e-mail.
|`cac:AccountingContact/cbc:Telephone`
|The telephone number for the accounting contact of the organization.
|`cac:AccountingContact/cbc:Telefax`
|The telefax number for the accounting contact of the organization.
|`cac:AccountingContact/cbc:ElectronicMail`
|The e-mail address for the accounting contact of the organization.
|===

*Example* +
_Party structure with both invoice recipient party and buyer party_
[source,xml]
----
<cac:AccountingCustomerParty> <!--1-->
    <cac:Party>
        <cbc:EndpointID schemeID="0088">1234567890123</cbc:EndpointID>
        <cac:PartyIdentification>
            <cbc:ID schemeID="0007">1234561234</cbc:ID>
        </cac:PartyIdentification>
        <cac:PartyName>
            <cbc:Name>Receiver Trading Name AB</cbc:Name>
        </cac:PartyName>
        <cac:PostalAddress>
            <cbc:StreetName>Street 32</cbc:StreetName>
            <cbc:AdditionalStreetName>Po box 878</cbc:AdditionalStreetName>
            <cbc:CityName>Stockholm</cbc:CityName>
            <cbc:PostalZone>123 12</cbc:PostalZone>
            <cac:Country>
                <cbc:IdentificationCode>SE</cbc:IdentificationCode>
            </cac:Country>
        </cac:PostalAddress>
        <cac:PartyTaxScheme>
            <cbc:CompanyID>SE123456789001</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>Receiver legal Name</cbc:RegistrationName>
            <cbc:CompanyID schemeID="0007">1234561234</cbc:CompanyID>
        </cac:PartyLegalEntity>
        <cac:Contact>
            <cbc:Name>Anders Andersson</cbc:Name>
            <cbc:Telephone>555444666</cbc:Telephone>
            <cbc:ElectronicMail>contact@receiver.com</cbc:ElectronicMail>
        </cac:Contact>
    </cac:Party>
</cac:AccountingCustomerParty>
<cac:BuyerCustomerParty> <!--2-->
    <cac:Party>
        <cac:PartyIdentification>
            <cbc:ID schemeID="0007">1111112222</cbc:ID>
        </cac:PartyIdentification>
        <cac:PartyName>
            <cbc:Name>Buyer Trading Name AB</cbc:Name>
        </cac:PartyName>
        <cac:PostalAddress>
            <cbc:StreetName>Street 32</cbc:StreetName>
            <cbc:AdditionalStreetName>Po box 878</cbc:AdditionalStreetName>
            <cbc:CityName>Stockholm</cbc:CityName>
            <cbc:PostalZone>123 12</cbc:PostalZone>
            <cac:Country>
                <cbc:IdentificationCode>SE</cbc:IdentificationCode>
            </cac:Country>
        </cac:PostalAddress>
        <cac:PartyTaxScheme>
            <cbc:CompanyID>SE111111222201</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>Buyer legal Name</cbc:RegistrationName>
            <cbc:CompanyID schemeID="0007">1111112222</cbc:CompanyID>
        </cac:PartyLegalEntity>
        <cac:Contact>
            <cbc:Name>Daniel Danielsson</cbc:Name>
            <cbc:Telephone>33322221111</cbc:Telephone>
            <cbc:ElectronicMail>contact@buyer.com</cbc:ElectronicMail>
        </cac:Contact>
    </cac:Party>
</cac:BuyerCustomerParty>
----
<1> Information in `cac:AccountingCustomerParty` will be used to identify the _receiver_ of the document.
<2> Information in `cac:BuyerCustomerParty` will be sent to the receiver as _buyer_ information.

WARNING: Please note that all e-invoice formats do not support both invoice recipient and buyer party information, therefore only use both structures when needed.
