In order to define the delivery in more detail, a new element to state a description of the delivery location has been added in `(Invoice|CreditNote)/cac:Delivery/cac:DeliveryLocation`.

Below table shows the definition of the added element.

.Elements added in cac:Delivery
|===
|Element |Description

|`cac:DeliveryLocation/cbc:Description`
|Text describing the delivery  location.
|`cac:DeliveryLocation/cac:Address/cbc:PostBox`
|The post box of the delivery location.
|`cac:DeliveryLocation/cac:Address/cbc:Department`
|The department of the delivery location.
|`cac:DeliveryLocation/cac:Address/cac:Country/cbc:Name`
|The country name of the delivery location.
|===

In addition, an extension has been created for providing additional information not supported in UBL 2.1. +

The UBL extension to be used for below elements is `(Invoice|CreditNote)/cac:Delivery/ext:UBLExtensions` and the structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/DeliveryExtension`. +

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<cac:Delivery>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DeliveryExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:DeliveryExtension/> <!--2-->
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:Delivery>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table show the definition of the additional elements added to the delivery extension.

.Elements added in puf:DeliveryExtension
|===
|Element |Description

|`puf:DeliveryMethod/cbc:Note`
|Description of the delivery method (free text).
|`puf:DeliveryMethod/puf:Code`
|A code for the delivery method.
|===

*Example* +
_Delivery method and code defined_
[source,xml]
----
<cac:Delivery>
    <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DeliveryExtension</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                  <puf:DeliveryExtension>
                      <puf:DeliveryMethod>
                          <cbc:Note>Text describing the delivery method</cbc:Note>
                          <puf:Code>Deliver Method Code</puf:Code>
                      </puf:DeliveryMethod>
                  </puf:DeliveryExtension>
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:Delivery>
----

Below table show the elements available in the party extension to be used in cac:Delivery/cac:DeliveryParty

.Elements added in puf:PartyExtension
|===
|Applicable XPath |Description

|`puf:ADAID/cbc:ID`
|Additional destination address identifier.
|`puf:ADAID/cbc:Name`
|Name of the additional destination unit.
|`puf:ADAID/puf:IDType`
|To identify the type of additional destination address identifier. The IDType must be coded using the <<_puf_002_adaid>> code list.
|`puf:ADAID/puf:IDType/@listID`
|IDType must have a list identifier attribute “PUF-002-ADAID”.
|===

===== Additional Destination Address Identifier (ADAID)

Additional Destination Address Identifier (ADAID) is used when there is a need to provide additional routing codes in order for the invoice to be sent to the correct recipient.
This is mostly used to public entities (e.g. government recipients). To identify the type of ADAID, the `puf:IDType` must be coded using the PUF-002-ADAID code list. See code list <<_puf_002_adaid>> for supported types of ADAID.


*Example*

[source,xml]
----
<cac:Delivery>
<!-- Code omitted for clarity -->
  <cac:DeliveryParty>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:PartyExtension</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:PartyExtension>
                        <puf:ADAID>
                            <cbc:ID>1234567890</cbc:ID>
                            <cbc:Name>Name of Unit</cbc:Name>
                            <puf:IDType listID="PUF-002-ADAID">GEN:UnitCode</puf:IDType>
                        </puf:ADAID>
                    </puf:PartyExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
  </cac:DeliveryParty>
<!-- Code omitted for clarity -->
</cac:Delivery>
----
