In order to define the delivery in more detail, a new element to state a description of the delivery location has been added in `(Invoice|CreditNote)/cac:Delivery/cac:DeliveryLocation`.

Below table shows the definition of the added element.

.Elements added in cac:Delivery
|===
|Element |Description

|`cac:DeliveryLocation/cbc:Description`
|Text describing the delivery  location.
|`cac:DeliveryLocation/cac:Address/cbc:PostBox`
|The post box of the delivery location.
|`cac:DeliveryLocation/cac:Address/cbc:Department`
|The department of the delivery location.
|`cac:DeliveryLocation/cac:Address/cac:Country/cbc:Name`
|The country name of the delivery location.
|===

In addition, an extension has been created for providing additional information not supported in UBL 2.1. +

The UBL extension to be used for below elements is `(Invoice|CreditNote)/cac:Delivery/ext:UBLExtensions` and the structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/DeliveryExtension`. +

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<cac:Delivery>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DeliveryExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:DeliveryExtension/> <!--2-->
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:Delivery>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table show the definition of the additional elements added to the extension.

.Elements added in puf:DeliveryExtension
|===
|Element |Description

|`puf:DeliveryMethod/cbc:Note`
|Description of the delivery method (free text).
|`puf:DeliveryMethod/puf:Code`
|A code for the delivery method.
|===

*Example* +
_Delivery method and code defined_
[source,xml]
----
<cac:Delivery>
    <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DeliveryExtension</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                  <puf:DeliveryExtension>
                      <puf:DeliveryMethod>
                          <cbc:Note>Text describing the delivery method</cbc:Note>
                          <puf:Code>Deliver Method Code</puf:Code>
                      </puf:DeliveryMethod>
                  </puf:DeliveryExtension>
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:Delivery>
----
