Pagero UF principally extends http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0] in two ways:

1. the use of additional segments/elements that are included in UBL 2.1, but excluded from the http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0]-subset of UBL 2.1.
2. via the use of https://wiki.oasis-open.org/ubl/UBLExtensions[UBL Extensions].

Pagero UF is to be considered as an extension, thus existing EN and Peppol rules may be overriden due to support extended content.

This chapter defines and specifies the available options of *adding information that is not available in the core PEPPOL BIS.* +

The chapter is divided into three parts for easier navigation:

1. <<_parties>> (specifies information related to party structure in UBL)
2. <<_document_level>> (specifies other information on header level)
3. <<_line_level>> (specifies information on line level)

WARNING: Note that most examples are only shown for document type Invoice.

=== Parties

include::parties.adoc[]

=== Document level

include::documentlevel.adoc[]

=== Line level

include::linelevel.adoc[]
