Pagero Universal Format, hereafter referred to as "Pagero UF", is developed and maintained by Pagero Group. Pagero UF is based on https://docs.oasis-open.org/ubl/UBL-2.1.html[Universal Business Language Version 2.1 (UBL 2.1)] and the http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0] format. +

To support the growing https://peppol.eu/[PEPPOL Network], Pagero UF has been built "on-top" of and fully support http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0], see section 3 for more information. +

To align with new regulations and the business needs that comes with the growing use of electronic invoices throughout the world, the core idea of Pagero UF is to present the opportunity to extend the content available in the http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0] as a means for supporting these market needs. +

To be able to provide the broadest support possible, Pagero UF has been designed with the following core basis in mind:

* https://standards.cen.eu/dyn/www/f?p=204:110:0::::FSP_PROJECT:60602&cs=1B61B766636F9FB34B7DBD72CE9026C72[European standard EN 16931-1:2017]

** EN 16931-1:2017 complies with the European Directive on electronic invoicing for public authorities (EN 2014/55 / ​​EU). It has been prepared by the Technical Committee TC434 at CEN by the European Commission.

*	http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0] (OpenPEPPOL´s CIUS (Core Invoice Usage Specifications) with EN16931 as the underlying specification)

*	Other https://ec.europa.eu/cefdigital/wiki/display/EINVCOMMUNITY/Community-driven+Registry+of+CIUS+(Core+Invoice+Usage+Specifications)+and+Extensions[CIUS´s] based on the regulations of https://standards.cen.eu/dyn/www/f?p=204:110:0::::FSP_PROJECT:60602&cs=1B61B766636F9FB34B7DBD72CE9026C72[EN 16931-1:2017]

* https://ec.europa.eu/cefdigital/wiki/display/EINVCOMMUNITY/Community-driven+Registry+of+CIUS+(Core+Invoice+Usage+Specifications)+and+Extensions[Extensions] based on the regulations of https://standards.cen.eu/dyn/www/f?p=204:110:0::::FSP_PROJECT:60602&cs=1B61B766636F9FB34B7DBD72CE9026C72[EN 16931-1:2017]

*	Country specific information found in domestic formats.

Based on extensive analysis of the above, Pagero UF has been designed to meet these country-, industry-, format- and/or system-specific requirements. +

Another intention of the Pagero UF has been to create a flexible, extendable format which can be updated quickly to be able to meet the requirements of the fast-changing global electronic document landscape.

'''

=== Version and Changelog

.Version
|===
|Version |Date |Description

|1.0
|2019-05-02
|First version published
|===
