This section contains information about requirements and other info concerning invoicing in Italy.

==== Routing code (Codice Destinatario)

In order to send invoices in Italy a destination code must be provided called "Codice Destinatario".

The destination code should be sent in `cac:AccountingCustomerParty/cac:Party/cbc:EndpointID` with schemeID "9921" (Indice delle Pubbliche Amministrazioni).

*Example*

[source,xml]
----
<cac:AccountingCustomerParty>
  <cac:Party>
    <cbc:EndpointID schemeID="9921">123456</cbc:EndpointID>
    <!-- Code omitted for clarity -->
  </cac:Party>
</cac:AccountingCustomerParty>
----

==== Duty Stamp (Dati Bollo)

The duty stamp amount should be provided in the extension block under Invoice, in the structure `(Invoice|CreditNote)/PageroExtension/DutyStamp`, see example below.

*Example* +
_Example from invoice_
[source,xml]
----
<Invoice>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:DutyStamp</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                  <puf:DutyStamp>
                      <puf:Amount currencyID="EUR">2.00</puf:Amount>
                  </puf:DutyStamp>
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:UBLVersionID>2.1</cbc:UBLVersionID>
  <!-- Code omitted for clarity -->
</Invoice>
----

==== Tax chargeability (Esigibilita IVA)

To provide tax chargeability, the extension element `(Invoice|CreditNote)/cac:TaxTotal/cac:TaxSubtotal/ext:UBLExtensions` can be used. The structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/TaxSubtotalExtension`. See example below:

Possible values to provide:

* *I* = VAT with immediate chargeability +
* *D* = VAT unrealized +
* *S* = Splitting of payments

*Example*
[source,xml]
----
<cac:TaxTotal>
    <cac:TaxSubtotal>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:TaxSubtotalExtension</ext:ExtensionURI>
                <ext:ExtensionContent>
                    <puf:PageroExtension>
                        <puf:TaxSubtotalExtension>
                          <puf:TaxChargeability>
                            <cbc:TaxTypeCode>S</cbc:TaxTypeCode>
                          </puf:TaxChargeability>
                        </puf:TaxSubtotalExtension>
                    </puf:PageroExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <!-- Code omitted for clarity -->
    </cac:TaxSubtotal>
</cac:TaxTotal>
----

==== VAT number and Fiscal Code

It is possible to send a VAT number and/or a Fiscal code (Codice Fiscale) in Pagero UF, below is a description and example how to provide this.

VAT number in Italy::
* CompanyID - _Must start with a country code (two characters) followed by 1 to 28 characters_ +
* TaxScheme/ID - _Must be VAT_
Fiscal code in Italy::
* CompanyID - _Can contain 11 to 16 characters_ +
* TaxScheme/ID - _Must be TAX_

*Example* +
_AccountingCustomerParty with both VAT number and Fiscal code_
[source,xml]
----
<cac:AccountingCustomerParty> <!--1-->
    <cac:Party>
        <!-- Code omitted for clarity -->
        <cac:PartyTaxScheme>
            <cbc:CompanyID>IT123456789</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyTaxScheme>
            <cbc:CompanyID>12345678901</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>TAX</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <!-- Code omitted for clarity -->
    </cac:Party>
</cac:AccountingCustomerParty>
----
<1> Example contains AccountingCustomerParty but same handling applies for AccountingSupplierParty

==== Registration data

To provide the registration data (Ufficio, NumeroREA, Capitale Sociale, Socio Unico and Stato Liquidazione) in the XML file please check
the extension for AccountingSupplierParty structure <<_registration_data, here>>.
