Below table lists all additional elements added within `Invoice/cac:InvoiceLine/cac:Item`, these additional fields is used to assign more detailed information for the article.

.Elements added in cac:InvoiceLine/cac:Item
|===
|Element |Description

|`cac:BuyersItemIdentification/cbc:ID`
|Identifier of the item, assigned by the buyer.
|`cac:ManufacturersItemIdentification/cbc:ID`
|Identifier of the item, assigned by the manufacturer.
|`cac:ItemInstance/cbc:ManufactureDate`
|Date of when the item was manufactured, date should be formatted yyyy-mm-dd.
|`cac:ItemInstance/cbc:BestBeforeDate`
|The items best before date, date should be formatted yyyy-mm-dd.
|`cac:ItemInstance/cbc:SerialID`
|Serial number of the item.
|`cac:ItemInstance/cac:LotIdentification/cbc:LotNumberID`
|Lot number identifier of the item.
|===

*Example*
[source,xml]
----
<cac:InvoiceLine>
  <!-- Code omitted for clarity -->
  <cac:Item>
    <cac:BuyersItemIdentification>
        <cbc:ID>Buyers item ID</cbc:ID>
    </cac:BuyersItemIdentification>
    <cac:ManufacturersItemIdentification>
        <cbc:ID>Manufacturers item ID</cbc:ID>
    </cac:ManufacturersItemIdentification>
    <cac:ItemInstance>
        <cbc:ManufactureDate>2018-01-01</cbc:ManufactureDate>
        <cbc:BestBeforeDate>2018-01-01</cbc:BestBeforeDate>
        <cbc:SerialID>123456789</cbc:SerialID>
        <cac:LotIdentification>
            <cbc:LotNumberID>1111111</cbc:LotNumberID>
        </cac:LotIdentification>
    </cac:ItemInstance>
  </cac:Item>
</cac:InvoiceLine>
----
