The LegalMonetaryTotal-UBLExtension provides the means to add more information about the total amount of the invoice. +

The UBL extension to be used for below elements is `(Invoice|CreditNote)/cac:LegalMonetaryTotal/ext:UBLExtensions` and the structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/LegalMonetaryTotalExtension`. +

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<cac:LegalMonetaryTotal>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LegalMonetaryTotalExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:LegalMonetaryTotalExtension/> <!--2-->
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:LegalMonetaryTotal>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table shows the definition of the new elements added to the extension.

.Elements added in puf:LegalMonetaryTotalExtension
|===
|Element |Description

|`puf:TaxCurrencyTaxExclusiveAmount`
|If the document currency and tax currency differs, Tax Exclusive Amount in Tax currency should be specified here.
|`puf:TaxCurrencyTaxExclusiveAmount/@currencyID`
|Currency of the Tax Currency Tax ExclusiveAmount.
|`puf:TaxCurrencyTaxInclusiveAmount`
|If the document currency and tax currency differs, Tax Inclusive Amount in Tax currency should be specified here.
|`puf:TaxCurrencyTaxInclusiveAmount/@currencyID`
|Currency of the Tax Currency TaxInclusive Amount.
|`puf:TaxCurrencyPayableAmount`
|If the document currency and tax currency differs, Payable Amount in Tax currency should be specified here.
|`puf:TaxCurrencyPayableAmount/@currencyID`
|Currency of the Tax Currency Payable Amount.
|`puf:PaymentInKind/puf:Amount`
|Payment in kind amount on invoice.
|`puf:PaymentInKind/puf:Amount/@currencyID`
|Currency of the Payment in kind amount.
|`puf:PaymentInKind/cbc:Note`
|Description of payment in kind.
|===

===== Tax currency amounts

This section show an example of how to provide the documents total amounts in its tax currency.

*Example* +
_Example with EUR as document currency and USD as Tax currency_
[source,xml]
----
<cbc:DocumentCurrencyCode listID="ISO4217">EUR</cbc:DocumentCurrencyCode>
<cbc:TaxCurrencyCode listID="ISO4217">USD</cbc:TaxCurrencyCode>
<!-- Code omitted for clarity -->
<cac:TaxExchangeRate>
  <cbc:SourceCurrencyCode listID="ISO4217">EUR</cbc:SourceCurrencyCode>
  <cbc:TargetCurrencyCode listID="ISO4217">USD</cbc:TargetCurrencyCode>
  <cbc:CalculationRate>1.16</cbc:CalculationRate> <!--1-->
  <cbc:MathematicOperatorCode>Multiply</cbc:MathematicOperatorCode>
  <cbc:Date>2017-12-01</cbc:Date>
</cac:TaxExchangeRate>
<!-- Code omitted for clarity -->
<cac:LegalMonetaryTotal>
  <ext:UBLExtensions>
      <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LegalMonetaryTotalExtension</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                  <puf:LegalMonetaryTotalExtension>
                      <puf:TaxCurrencyTaxExclusiveAmount currencyID="USD">116.00</puf:TaxCurrencyTaxExclusiveAmount> <!--2-->
                      <puf:TaxCurrencyTaxInclusiveAmount currencyID="USD">116.00</puf:TaxCurrencyTaxInclusiveAmount> <!--3-->
                      <puf:TaxCurrencyPayableAmount currencyID="USD">116.00</puf:TaxCurrencyPayableAmount> <!--4-->
                  </puf:LegalMonetaryTotalExtension>
              </puf:PageroExtension>
          </ext:ExtensionContent>
      </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:TaxExclusiveAmount currencyID="EUR">100.00</cbc:TaxExclusiveAmount>
  <cbc:TaxInclusiveAmount currencyID="EUR">100.00</cbc:TaxInclusiveAmount>
  <cbc:PayableAmount currencyID="EUR">100.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
----
<1> Exchange rate which the calculation is based upon.
<2> Amount in tax currency calculated upon `TaxExclusiveAmount` and `CalculationRate`.
<3> Amount in tax currency calculated upon `TaxInclusiveAmount` and `CalculationRate`.
<4> Amount in tax currency calculated upon `PayableAmount` and `CalculationRate`.

NOTE: Please note that tax has been excluded in above example.

===== Payment in Kind

Payment in kind is a way to use goods or services as payment instead of a cash. +
The elements available in Pagero UF allow the possibility to provide the corresponding amount of the goods and services and a description.

*Example* +
_Payment In Kind is 100 EUR_
[source,xml]
----
<cac:TaxTotal>
    <cbc:TaxAmount currencyID="EUR">250</cbc:TaxAmount>
    <cac:TaxSubtotal>
        <cbc:TaxableAmount currencyID="EUR">1000</cbc:TaxableAmount>
        <cbc:TaxAmount currencyID="EUR">250</cbc:TaxAmount>
        <cac:TaxCategory>
            <cbc:ID>S</cbc:ID>
            <cbc:Percent>25.00</cbc:Percent>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:TaxCategory>
    </cac:TaxSubtotal>
</cac:TaxTotal>
<cac:LegalMonetaryTotal>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LegalMonetaryTotalExtension</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:LegalMonetaryTotalExtension>
                        <puf:PaymentInKind>
                            <puf:Amount currency="EUR">100</puf:Amount> <!--1-->
                            <cbc:Note>Text describing the payment in kind</cbc:Note>
                        </puf:PaymentInKind>
                    </puf:LegalMonetaryTotalExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <cbc:LineExtensionAmount currencyID="EUR">1000</cbc:LineExtensionAmount>
    <cbc:TaxExclusiveAmount currencyID="EUR">1000</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="EUR">1250</cbc:TaxInclusiveAmount>
    <cbc:PayableAmount currencyID="EUR">1150</cbc:PayableAmount> <!--2-->
</cac:LegalMonetaryTotal>
----
<1> The amount 100 EUR is the payment in kind.
<2> 100 EUR is subtracted on the TaxInclusiveAmount, calculation 1250 - 100 = 1150, resulting in new Payable amount.
