To be able to provide additional references on line level according to the list defined in the PEPPOL BIS Billing 3.0 specification chapter link:http://docs.PEPPOL.eu/poacc/billing/3.0/bis/#_invoiced_object_identifier[10.3.3].

.Elements added in additional document reference extension
|===
|Element |Description

|cbc:ID
|Identifier of the referenced document
|cbc:ID/@schemeID
|Type of reference, must be according to link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred1153.htm[UN/CEFACT 1153 code list]
|cbc:DocumentTypeCode
|Must be "130" to state that it's an invoice object reference
|===

The UBL extension to be used for this is is Invoice/cac:InvoiceLine/ext:UBLExtensions and the structure used from PUF-ExtensionComponent.xsd is PageroExtension/LineExtension.
See example below as well as the URI to be used for this extension.

*Example* +
_Example with delivery note identifier as ID_
[source,xml]
----
<cac:InvoiceLine>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:LineExtension>
                        <puf:AdditionalDocumentReference> <!--2-->
                            <cbc:ID schemeID="DQ">Delivery Note Identifier</ID>
                            <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
                        </puf:AdditionalDocumentReference>
                    </puf:LineExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:InvoiceLine>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.
