To be able to further define delivery information, the possibility to provide it for each line has been added in the structure `Invoice/cac:InvoiceLine/cac:Delivery`.

See table below for definition of the new elements.

.Elements added to cac:InvoiceLine/cac:Delivery
|===
|Element |Description

|`cbc:Quantity`
|Delivered quantity.
|`cbc:Quantity/@unitCode`
|Unit of the delivered quantity.
|`cbc:ActualDeliveryDate`
|Date of delivery.
|`cac:DeliveryLocation/cbc:ID`
|ID of the delivery location.
|`cac:DeliveryLocation/cbc:ID/@schemeID`
|Party Identifier Scheme MUST be coded using one of the ISO 6523 ICD list.
|`cac:DeliveryLocation/cac:Address/cbc:StreetName`
|Street name of the delivery location.
|`cac:DeliveryLocation/cac:Address/cbc:AdditionalStreetName`
|Additional street name of the delivery location.
|`cac:DeliveryLocation/cac:Address/cbc:CityName`
|City of the delivery location.
|`cac:DeliveryLocation/cac:Address/cbc:PostalZone`
|Post code of the delivery location.
|`cac:DeliveryLocation/cac:Address/cbc:CountrySubentity`
|Province of the delivery location.
|`cac:DeliveryLocation/cac:Address/cac:Country/cbc:IdentificationCode`
|Country code of the delivery location.
|`cac:DeliveryLocation/cac:Address/cac:Country/cbc:Name`
|The country name of the delivery location.
|===

*Example* +
_Invoice example of delivery on line_
[source,xml]
----
<cac:InvoiceLine>
  <!-- Code omitted for clarity -->
  <cac:Delivery>
    <cbc:Quantity unitCode="PCE">1</cbc:Quantity>
    <cbc:ActualDeliveryDate>2019-01-25</cbc:ActualDeliveryDate>
    <cac:DeliveryLocation>
        <cbc:ID schemeID="0088">0000000000000</cbc:ID>
        <cac:Address>
            <cbc:StreetName>Delivery Street</cbc:StreetName>
            <cbc:CityName>Delivery City</cbc:CityName>
            <cbc:PostalZone>12345</cbc:PostalZone>
            <cbc:CountrySubentity>Delivery Province</cbc:CountrySubentity>
            <cac:Country>
                <cbc:IdentificationCode listID="ISO3166-1:Alpha2">SE</cbc:IdentificationCode>
                <cbc:Name>Sweden</cbc:Name>
            </cac:Country>
        </cac:Address>
    </cac:DeliveryLocation>
  </cac:Delivery>
  <!-- Code omitted for clarity -->
</cac:InvoiceLine>
----
