In order to define more details regarding the order, possibility to provide date of the purchase order and sales order date has been added.

Below show how additional element from UBL 2.1 in `(Invoice|CreditNote)/cac:OrderReference` has been used to provide the purchase order date.

.Elements added in cac:OrderReference
|===
|Element |Description

|`cbc:IssueDate`
|Date of issue of the referenced purchase order, date should be formatted yyyy-mm-dd.
|===

In addition, an extension has been created for providing sales order date not supported in UBL 2.1. +

The UBL extension to be used for below elements is `(Invoice|CreditNote)/cac:OrderReference/ext:UBLExtensions` and the structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/OrderReferenceExtension`. +

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<cac:OrderReference>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:OrderReferenceExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:OrderReferenceExtension/> <!--2-->
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</cac:OrderReference>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table show the definition of the new element added to the extension.

.Elements added in puf:OrderReferenceExtension
|===
|Element |Description

|`puf:SalesOrderIssueDate`
|Date of the sales order, date should be formatted yyyy-mm-dd.
|===

*Example* +
_Order reference containing all information available_
[source,xml]
----
<cac:OrderReference>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:OrderReferenceExtension</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:OrderReferenceExtension>
                        <puf:SalesOrderIssueDate>2019-01-01</puf:SalesOrderIssueDate>
                    </puf:OrderReferenceExtension>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <cbc:ID>Purchase Order ID</cbc:ID>
    <cbc:SalesOrderID>Sales Order ID</cbc:SalesOrderID>
    <cbc:IssueDate>2019-01-01</cbc:IssueDate>
</cac:OrderReference>
----
