If there are multiple orders that needs to be referenced, `cac:OrderLineReference` can be used. Below table shows the new elements added within the `Invoice/cac:InvoiceLine/cac:OrderLineReference`-segment.

.Elements added to cac:OrderLineReference
|===
|Element |Description

|`cac:OrderReference/cbc:ID`
|Identification of the referenced purchase order, assigned by the buyer.
|`cac:OrderReference/cbc:SalesOrderID`
|Identification of the referenced sales order, assigned by the seller.
|`cac:OrderReference/cbc:IssueDate`
|Date of issue of the referenced purchase order, date should be formatted yyyy-mm-dd.
|===

In addition, an extension has been created for providing additional information not supported in UBL 2.1. +

The UBL extension to be used for below elements is `Invoice/cac:InvoiceLine/cac:OrderLineReference/cac:OrderReference/ext:UBLExtensions` and the structure used from `PUF-ExtensionComponent.xsd` is
`PageroExtension/LineExtension`. +

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<cac:InvoiceLine>
    <cac:OrderLineReference>
        <cac:OrderReference>
            <ext:UBLExtensions>
                <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI> <!--1-->
                    <ext:ExtensionContent>
                        <puf:PageroExtension>
                            <puf:LineExtension>
                                <puf:OrderLineReference/> <!--2-->
                            </puf:LineExtension>
                        </puf:PageroExtension>
                    </ext:ExtensionContent>
                </ext:UBLExtension>
            </ext:UBLExtensions>
            <!-- Code omitted for clarity -->
        </cac:OrderLineReference>
    </cac:OrderReference>
</cac:InvoiceLine>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table show the definition of the new element added to the extension.

.Elements added in puf:OrderLineReference
|===
|Element |Description

|`puf:SalesOrderIssueDate`
|Date of the sales order, date should be formatted yyyy-mm-dd.
|===

*Example* +
_Order line reference containing all available elements_
[source,xml]
----
<cac:InvoiceLine>
    <!-- Code omitted for clarity -->
    <cac:OrderLineReference>
        <cbc:LineID>1</cbc:LineID>
        <cac:OrderReference>
            <ext:UBLExtensions>
                <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:LineExtension</ext:ExtensionURI>
                    <ext:ExtensionContent>
                        <puf:PageroExtension>
                            <puf:LineExtension>
                                <puf:OrderLineReference>
                                    <puf:SalesOrderIssueDate>2019-01-01</puf:SalesOrderIssueDate>
                                </puf:OrderLineReference>
                            </puf:LineExtension>
                        </puf:PageroExtension>
                    </ext:ExtensionContent>
                </ext:UBLExtension>
            </ext:UBLExtensions>
            <cbc:ID>Purchase Order ID</cbc:ID>
            <cbc:SalesOrderID>Sales Order ID</cbc:SalesOrderID>
            <cbc:IssueDate>2019-01-01</cbc:IssueDate>
        </cac:OrderReference>
    </cac:OrderLineReference>
    <!-- Code omitted for clarity -->
</cac:InvoiceLine>
----
