The aim for Pagero Universal is to cover invoicing and business requirements in legal domains and countries all over the world.
The below list should be seen as an overview to visualize where PUF currently is considered applicable. If the country is marked as supported
means that an analysis of country or regional requirements has been made. It does however not automatically mean that all conceivable
content requirements are supported within PUF. +

If a country is not in the list does not necessarily mean that Pagero Universal format cannot be used in the specific region but it means that
no extensive analysis has been done of the requirements. The list of supported countries/regions are updated continuously as Pagero Universal Format
is developed to follow new identified markets/requirements.

=== Country list

.Table of supported countries
[%autowidth.stretch]
|===
|Country |Require ext:UBLExtensions |Comment

|Australia
|*No*
|

|Austria
|*No*
|

|Belgium
|*No*
|

|Canada
|*No*
|

|Denmark
|*No*
|

|Croatia
|*No*
|

|Finland
|*No*
|

|France
|*Yes*
|

|Germany
|*No*
|

|India
|*Yes*
|

|Ireland
|*No*
|

|Italy
|*Yes*
|

|Lithuania
|*No*
|

|Netherlands
|*No*
|Only Invoice and Credit note support

|Norway
|*No*
|

|Portugal
|*Yes*
|

|Saudi Arabia
|*Yes*
|

|Singapore
|*No*
|

|Spain
|*Yes*
|

|Sweden
|*No*
|

|United Kingdom
|*No*
|

|===
