To avoid any confustion between these industry specific extensions and the regular PUF extensions a new schema is provided to
get a clear overview of which industry specific values are possible to provide (PUF-ExtensionComponentIndustrySpecific.xsd).
To be able to use the PUF-ExtensionComponentIndustrySpecific a namespace must be included in the document file.
See chapter <<_6_0_xml_schemas, 6.0>> for xsd.

*Example*
[source,xml]
----
<Invoice
  ...
  xmlns:pufind="urn:pagero:ExtensionComponentIndustrySpecific:1.0">
----

The Industry specific values are in the schema sorted on type of business (e g. Advertising, Energy etc).
To use the industry specification extension the URI to be used is:

*Example*
_Invoice with industry specific information in the element of advertising on line level._
[source,xml]
----
<cac:InvoiceLine>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponentIndustrySpecific:1.0:PageroExtensionIndustrySpecific:Advertising</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <pufind:PageroExtensionIndustrySpecific>
                    <pufind:Advertising>
                        <pufind:Advertisement/> <!--2-->
                    </pufind:LineExtension>
                </pufind:PageroExtensionIndustrySpecific>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    ...
</cac:InvoiceLine>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.


=== 9.1 Industry Specific - Advertising
.Elements added to Industry specific extension - Advertising
|===
|Element |Description

|pufind:Advertising/pufind:Advertisement/pufind:AdvertisementType
|Type of ad, e.g. BANNER or GATEFOLD
|pufind:Advertising/pufind:Advertisement/pufind:AdvertisementType/@listID
|The AdvertisementType must have a list identifier attribute <<_9_2_1_puf_001_advertisingtype, PUF-001-ADVERTISINGTYPE>>.
|pufind:Advertising/pufind:Advertiser/cbc:Name
|Name of advertiser/advertising agency.
|pufind:Advertising/pufind:Booking/pufind:BookingDate
|Date when booked
|pufind:Advertising/pufind:Brand/cbc:Name
|Name of brand
|pufind:Advertising/pufind:Media/pufind:MediaType
|Type of media, e.g. CABLE_TV or MAGAZINE
|pufind:Advertising/pufind:Publication/cbc:ID
|ID/Code for publication
|pufind:Advertising/pufind:Publication/cbc:name
|Name of publication
|===

==== 9.1.1  Advertising Type
The advertising type is specified using the pufind:Advertising/pufind:Advertisement/pufind:AdvertisementType element. The attribute listID must indicate the list used. In this case
PUF-001-ADVERTISINGTYPE. The value in AdvertisementType must be from the list <<_9_2_1_puf_001_advertisingtype, PUF-001-ADVERTISINGTYPE>>.

*Example*
_Invoice with the Advertisement Type specified on line level._
[source,xml]
----
<cac:InvoiceLine>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponentIndustrySpecific:1.0:PageroExtensionIndustrySpecific:Advertising</ext:ExtensionURI> <!--1-->
            <ext:ExtensionContent>
                <pufind:PageroExtensionIndustrySpecific>
                    <pufind:Advertising>
                        <pufind:Advertisement>
                          <pufind:AdvertisementType listID="PUF-001-ADVERTISINGTYPE">POLYBAG</pufind:AdvertisementType>
                        </pufind:Advertisement>
                    </pufind:LineExtension>
                </pufind:PageroExtensionIndustrySpecific>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    ...
</cac:InvoiceLine>
----

=== 9.2 Code lists for coded elements - Industry Specific

.Table of the code lists used
|===
|Business Term |Xpath |listID

|Advertisment type
|pufind:Advertising/pufind:Advertisement/pufind:AdvertisementType/@listID
|<<_9_2_1_puf_001_advertisingtype, PUF-001-ADVERTISINGTYPE>>.
|===

==== 9.2.1 PUF-001-ADVERTISINGTYPE
|===
|Value |Description

|AMBIENT
|Defines the type of ad

|BANNER
|Defines the type of ad

|BELLY_BAND
|Defines the type of ad

|BUTTON
|Defines the type of ad

|CABLE
|Defines the type of ad

|CLASSIFIED
|Defines the type of ad

|CLASSIFIED_DISPLAY
|Defines the type of ad

|DISPLAY
|Defines the type of ad

|EMAIL
|Defines the type of ad

|GATEFOLD
|Defines the type of ad

|INSERT
|Defines the type of ad

|INTERACTIVE
|Defines the type of ad

|INTERACTIVE_CLASSIFIED
|Defines the type of ad

|INTERACTIVE_DISPLAY
|Defines the type of ad

|MAGAZINE
|Defines the type of ad

|MAGAZINE_CLASSIFIED
|Defines the type of ad

|MAGAZINE_CLASSIFIED_DISPLAY
|Defines the type of ad

|MAGAZINE_DISPLAY
|Defines the type of ad

|MMS
|Defines the type of ad

|NEWSPAPER
|Defines the type of ad

|NEWSPAPER_CLASSIFIED
|Defines the type of ad

|NEWSPAPER_CLASSIFIED_DISPLAY
|Defines the type of ad

|NEWSPAPER_DISPLAY
|Defines the type of ad

|ONLINE_VIDEO
|Defines the type of ad

|ONSERT
|Defines the type of ad

|OUTDOOR
|Defines the type of ad

|OUTDOOR_ALTERNATIVE
|Defines the type of ad

|OUTDOOR_ALTERNATIVE_DIGITAL
|Defines the type of ad

|OUTDOOR_BILLBOARD
|Defines the type of ad

|OUTDOOR_BILLBOARD_DIGITAL
|Defines the type of ad

|OUTDOOR_STREET_FURNITURE
|Defines the type of ad

|OUTDOOR_STREET_FURNITURE_DIGITAL
|Defines the type of ad

|OUTDOOR_TRANSIT
|Defines the type of ad

|OUTDOOR_TRANSIT_DIGITAL
|Defines the type of ad

|PHONE
|Defines the type of ad

|POLYBAG
|Defines the type of ad

|POPUP
|Defines the type of ad

|RADIO
|Defines the type of ad

|RICH_MEDIA
|Defines the type of ad

|SMS
|Defines the type of ad

|SPADEA
|Defines the type of ad

|SPONSORSHIP
|Defines the type of ad

|STICKY_NOTE
|Defines the type of ad

|TELEVISION
|Defines the type of ad

|ZZZ
|Defines the type of ad

|===
