This section contains information about requirements and other info concerning invoicing in Sweden.

==== 4.1.1 Buyer Reference
In sweden this is often referred to as your reference or customer reference (Beställarreferens/Er referens).
If there is a need to provide a buyer reference this should be done in `Invoice/cbc:BuyerReference`.


==== 4.1.2 Bankgiro
In order to provide the Bankgiro account use `SE:Bankgiro` as `PaymentChannelCode`. The BIC for bankgiro is BGABSESS.

*Example*

[source,xml]
----
<cac:PaymentMeans>
    <cbc:PaymentMeansCode listID="UNCL4461">30</cbc:PaymentMeansCode>
    <cbc:PaymentDueDate>2017-10-31</cbc:PaymentDueDate>
    <cbc:PaymentChannelCode>SE:Bankgiro</cbc:PaymentChannelCode>
    <cac:PayeeFinancialAccount>
        <cbc:ID schemeID="LOCAL">11111111</cbc:ID> <!--1-->
        <cac:FinancialInstitutionBranch>
            <cac:FinancialInstitution>
                <cbc:ID schemeID="BIC">BGABSESS</cbc:ID>
            </cac:FinancialInstitution>
        </cac:FinancialInstitutionBranch>
    </cac:PayeeFinancialAccount>
</cac:PaymentMeans>
----
<1> Provide the Bankgiro account number in cbc:ID


==== 4.1.3 Plusgiro
In order to provide the Plusgiro account use `SE:Plusgiro` as `PaymentChannelCode`. The BIC for plusgiro is `PGSISESS`.

*Example*

[source,xml]
----

<cac:PaymentMeans>
    <cbc:PaymentMeansCode listID="UNCL4461">30</cbc:PaymentMeansCode>
    <cbc:PaymentDueDate>2017-10-31</cbc:PaymentDueDate>
    <cbc:PaymentChannelCode>SE:Plusgiro</cbc:PaymentChannelCode>
    <cac:PayeeFinancialAccount>
        <cbc:ID schemeID="LOCAL">1111111</cbc:ID> <!--1-->
        <cac:FinancialInstitutionBranch>
            <cac:FinancialInstitution>
                <cbc:ID schemeID="BIC">PGSISESS</cbc:ID>
            </cac:FinancialInstitution>
        </cac:FinancialInstitutionBranch>
    </cac:PayeeFinancialAccount>
</cac:PaymentMeans>
----
<1> Provide the Plusgiro account number in cbc:ID

==== 4.1.4 Vat Registration Text
In order to provide the sellers vat registration text (Godkänd för F-skatt) use the `Invoice/cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID` element. Note that the element
`Invoice/cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:ID` must equal "TAX".

*Example*

[source,xml]
----
<cac:AccountingSupplierParty>
    ...
    <cac:PartyTaxScheme> <!--1-->
            <cbc:CompanyID>SE000000000001</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
    </cac:PartyTaxScheme>
    <cac:PartyTaxScheme>
            <cbc:CompanyID>Godkänd för F-skatt</cbc:CompanyID> <!--2-->
            <cac:TaxScheme>
                <cbc:ID>TAX</cbc:ID> <!--3-->
            </cac:TaxScheme>
    </cac:PartyTaxScheme>
    ...
</cac:AccountingSupplierParty>
----
<1> VAT number can be provided in a separate PartyTaxScheme
<2> Information regarding tax registration
<3> Value must be "TAX"
