An extension has been created for providing additional information not supported in UBL 2.1. +

The UBL extension to be used for below elements is `(Invoice|CreditNote)/cac:TaxTotal/cac:TaxSubtotal/ext:UBLExtensions` and the structure used from `PUF-ExtensionComponent.xsd` is `PageroExtension/TaxSubtotalExtension`. +

See example below as well as the URI to be used for this extension.

*Example*
[source,xml]
----
<cac:TaxTotal>
    <cac:TaxSubtotal>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:TaxSubtotalExtension</ext:ExtensionURI> <!--1-->
                <ext:ExtensionContent>
                    <puf:PageroExtension>
                        <puf:TaxSubtotalExtension/> <!--2-->
                    </puf:PageroExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <!-- Code omitted for clarity -->
    </cac:TaxSubtotal>
</cac:TaxTotal>
----
<1> URI to be used if this extension is added.
<2> Structure to be used if information from this extension will be used.

Below table lists all additional elements added to the extension.

.Elements added in puf:TaxSubtotalExtension
|===
|Element |Description

|`puf:TaxCurrencyTaxableAmount`
|Taxable amount in tax currency per subtotal
|`puf:TaxCurrencyTaxAmount`
|Tax amount in tax currency per subtotal
|`puf:TaxChargeability/cbc:TaxTypeCode`
|Chargeability per tax (see Italy section <<_tax_chargeability_esigibilita_iva, here>>)
|`puf:EquivalenceSurcharge/cbc:Percent`
|Percentage  of equivalence surcharge
|`puf:EquivalenceSurcharge/puf:Amount`
|Sum of equivalence surcharge amounts  assigned to items containing same tax rate
|`puf:EquivalenceSurcharge/puf:Amount/@currencyID`
|Currency of the amount
|===

===== Equivalence Surcharge

Equivalence Surcharge is applied to a Tax Rate in its sub total segment, the calculation is done on the taxable amount for the corresponding tax.
The total tax amount including the surcharge, is then applied to the total TaxAmount-element summarized based on all TaxSubtotals taxamounts.

See example below.

*Example* +
_Invoice with equivalence surcharge of 1.5 %_
[source,xml]
----
<cac:TaxTotal>
    <cbc:TaxAmount currencyID="EUR">26.50</cbc:TaxAmount> <!--1-->
    <cac:TaxSubtotal>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:TaxSubtotalExtension</ext:ExtensionURI>
                <ext:ExtensionContent>
                    <puf:PageroExtension>
                        <puf:TaxSubtotalExtension>
                            <puf:EquivalenceSurcharge>
                                <cbc:Percent>1.5</cbc:Percent> <!--3-->
                                <puf:Amount currencyID="EUR">1.5</puf:Amount> <!--4-->
                            </puf:EquivalenceSurcharge>
                        </puf:TaxSubtotalExtension>
                    </puf:PageroExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
        <cbc:TaxAmount currencyID="EUR">25.00</cbc:TaxAmount> <!--2-->
        <cac:TaxCategory>
            <cbc:ID schemeID="UNCL5305">S</cbc:ID>
            <cbc:Percent>25.00</cbc:Percent>
            <cac:TaxScheme>
                <cbc:ID schemeID="UN/ECE 5153">VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:TaxCategory>
    </cac:TaxSubtotal>
</cac:TaxTotal>
----
<1> The tax amount including all EquivalenceSurcharge/Amount and TaxAmounts
<2> The tax amount for the corresponding TaxSubtotal without any EquivalenceSurcharge
<3> The percentage of the surcharge applied for the Taxsubtotal
<4> The amount of surcharge applied for the TaxSubtotal

===== Tax currency amounts

In Peppol BIS 3.0 billing it's only possible to provide the tax currency amount summary of all sub totals. In order to extend the support, it's possible to use PUF extension to provide the taxable and tax amount in tax currency per each sub total. See example below.

*Example*
[source,xml]
----
<cbc:DocumentCurrencyCode listID="ISO4217">EUR</cbc:DocumentCurrencyCode>
<cbc:TaxCurrencyCode listID="ISO4217">USD</cbc:TaxCurrencyCode>
<!-- Code omitted for clarity -->
<cac:TaxExchangeRate>
  <cbc:SourceCurrencyCode listID="ISO4217">EUR</cbc:SourceCurrencyCode>
  <cbc:TargetCurrencyCode listID="ISO4217">USD</cbc:TargetCurrencyCode>
  <cbc:CalculationRate>1.17</cbc:CalculationRate>
  <cbc:MathematicOperatorCode>Multiply</cbc:MathematicOperatorCode>
  <cbc:Date>2019-01-01</cbc:Date>
</cac:TaxExchangeRate>
<!-- Code omitted for clarity -->
<cac:TaxTotal>
    <cbc:TaxAmount currencyID="EUR">37.00</cbc:TaxAmount>
    <cac:TaxSubtotal>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:TaxSubtotalExtension</ext:ExtensionURI>
                <ext:ExtensionContent>
                    <puf:PageroExtension>
                        <puf:TaxSubtotalExtension>
                            <puf:TaxCurrencyTaxableAmount currencyID="USD">117.00</puf:TaxCurrencyTaxableAmount> <!--1-->
                            <puf:TaxCurrencyTaxAmount currencyID="USD">29.25</puf:TaxCurrencyTaxAmount> <!--2-->
                        </puf:TaxSubtotalExtension>
                    </puf:PageroExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
        <cbc:TaxAmount currencyID="EUR">25.00</cbc:TaxAmount>
        <cac:TaxCategory>
            <cbc:ID schemeID="UNCL5305">S</cbc:ID>
            <cbc:Percent>25</cbc:Percent>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:TaxCategory>
    </cac:TaxSubtotal>
    <cac:TaxSubtotal>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:TaxSubtotalExtension</ext:ExtensionURI>
                <ext:ExtensionContent>
                    <puf:PageroExtension>
                        <puf:TaxSubtotalExtension>
                            <puf:TaxCurrencyTaxableAmount currencyID="USD">117.00</puf:TaxCurrencyTaxableAmount> <!--3-->
                            <puf:TaxCurrencyTaxAmount currencyID="USD">14.04</puf:TaxCurrencyTaxAmount> <!--4-->
                        </puf:TaxSubtotalExtension>
                    </puf:PageroExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
        <cbc:TaxAmount currencyID="EUR">12.00</cbc:TaxAmount>
        <cac:TaxCategory>
            <cbc:ID schemeID="UNCL5305">S</cbc:ID>
            <cbc:Percent>12</cbc:Percent>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:TaxCategory>
    </cac:TaxSubtotal>
</cac:TaxTotal>
<cac:TaxTotal>
    <cbc:TaxAmount currencyID="USD">43.29</cbc:TaxAmount> <!--5-->
</cac:TaxTotal>
----
<1> Taxable amount in tax currency for 25 % rate
<2> Tax amount in tax currency for 25 % rate
<3> Taxable amount in tax currency for 12 % rate
<4> Tax amount in tax currency for 12 % rate
<5> Summary of each sub totals tax currency amount
