This section contains information about special requirements concerning invoicing in Portugal.

==== Billing software certification

Invoices in Portugal must be issued via a certified software and in the extension `puf:BillingSoftware` it's possible to provide the mandatory values.

*Example* +
_Extension with the billing software details populated_
[source,xml]
----
<Invoice>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:BillingSoftware</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:BillingSoftware>
                        <puf:Number>1111/AT</puf:Number> <!--1-->
                        <puf:Hash>AAaa</puf:Hash> <!--2-->
                        <cbc:Description>AAaa - Processado por programa certificado n. 1111/AT.</cbc:Description> <!--3-->
                    </puf:BillingSoftware>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!-- Code omitted for clarity -->
</Invoice>

----
<1> Software certification identification.
<2> Hash code.
<3> Description of the software certification.

==== QR code and ATCUD

In Portugal it can be required to provide a QR code and ATCUD. 

There are two ways of providing a QR string in PUF. Note that you should only use **one** of the alternatives.




*Example 1. As mentioned in the national CIUS-PT.* +
_In this example the QR code and ATCUD is provided in cac:AdditionalDocumentReference provided as recommended in the portuguese national cius (CIUS-PT). This way of sending the QR can be used if
the issuer is sending an Invoice Image that contains a qr image that corresponds to the the embedded qr string in below example._
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:AdditionalDocumentReference>
        <cbc:ID schemeID="ANG">12345678-123456789123</cbc:ID> <!--ATCUD, use the schemeID ANG-->
        <cbc:DocumentDescription>QR_CODE</cbc:DocumentDescription><!-- DocumentDescription must be QR_CODE -->
        <cac:Attachment> <!--QR Code encoded in base64-->
            <cbc:EmbeddedDocumentBinaryObject mimeCode="text/plain" filename="the filename">QRstringInBase64</cbc:EmbeddedDocumentBinaryObject><!-- mimeCode must be text/plain -->
        </cac:Attachment>
    </cac:AdditionalDocumentReference>
    <!-- Code omitted for clarity -->
</Invoice>
----

*Example 2. Alternate way of sending QR string and ATCUD* +
If there is a need for providing a QR code that is to be used by Pagero in order to display it on an invoice presentation/image. If this is the case the below example is to visualize how QR and ATCUD
can be provided. Note that in this scenario the QR string must be sent as plain TEXT and not as base64._
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:QRExtension</ext:ExtensionURI>
      <ext:ExtensionContent>
        <puf:PageroExtension>
          <puf:SupplierGeneratedQRString>
            <puf:QRString>TheQRCode</puf:QRString>
            <puf:QREncodingType>TEXT</puf:QREncodingType>
          </puf:SupplierGeneratedQRString>
        </puf:PageroExtension>
      </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <!-- Code omitted for clarity --> 
  <cac:AdditionalDocumentReference>
        <cbc:ID schemeID="ANG">12345678-123456789123</cbc:ID> <!--ATCUD, use the schemeID ANG-->
    </cac:AdditionalDocumentReference>
    <!-- Code omitted for clarity -->
</Invoice>
----

==== Tax category codes

Tax category codes for Portugal can be found here: https://pagero.github.io/puf-code-lists/#_tax_category_codes_portugal[Tax category codes Portugal^]. 

Note that multiple tax category codes overlap due to previous Portugese standards. The recommendation is to use the official UNCL5305 codes in the list, if possible.
