This section contains information about special requirements concerning invoicing in Türkiye.

==== Invoice profile id

For the UBL-TR format in Türkiye, it is mandatory to specify the invoice profile that's used.  

Valid values are listed in the table below: 

|===
|Value |Description

|`TICARIFATURA`
|Commercial invoice.

|`TEMELFATURA`
|Basic invoice.

|`EARSIVFATURA`
|e-Archive invoice.

|`IHRACAT`
|Goods export invoice.

|===

*Example* +
_Invoice profile example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:RestrictedInformation</ext:ExtensionURI>
            <ext:ExtensionContent>
                <puf:PageroExtension>
                    <puf:RestrictedInformation>
                        <puf:Key>UBLTRProfile</puf:Key>
                        <puf:Value>TICARIFATURA</puf:Value>
                    </puf:RestrictedInformation>
                </puf:PageroExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>   
  <!-- Code omitted for clarity -->
</Invoice>
----

==== Invoice type code

In addition to the invoice profile, it is also required to indicate the invoice type. This should be indicated in the attribute `name`` belonging to the element `cbc:InvoiceTypeCode`.

Valid values are listed in the table below: 

|===
|Value |Description

|`SATIS`
|Sales invoice (seller-buyer).

|`IADE`
|Return invoice (buyer-seller).

|`TEVKIFAT`
|Invoice with withholding tax.

|`ISTISNA`
|Invoice with VAT Exemption.

|`OZELMATRAH`
|Private bills.

|`IHRACKAYITLI`
|Export sales.

|===

*Example* +
_Invoice type code example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cbc:InvoiceTypeCode name="SATIS">380</cbc:InvoiceTypeCode> <!--1-->
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> Note that in Türkiye, credit notes do not exist and instead a return invoice (`IADE`), from buyer to seller, should be used. This means that the actual value of `cbc:InvoiceTypeCode` should be `380`, even for `IADE` invoices. 

==== Invoice delivery method

If the invoice profile id is set as "EARSIVFATURA" it is mandatory to include how the invoice is being distributed. 
There are only two allowed values. If Pagero is to do the invoice distribution, you should always enter "ELEKTRONIK". 
If an e-mail address for the buyer exists (see `cac:AccountingContact/cbc:ElectronicMail` in <<_cacaccountingcustomerparty>>) in the invoice and no delivery method value is sent, Pagero will default to "ELEKTRONIK". 

|===
|Value |Description

|`KAGIT`
|Paper.

|`ELEKTRONIK`
|Electronically.

|===

*Example* +
_Invoice Delivery Method example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <ext:UBLExtensions>
    <ext:UBLExtension>
        <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:RestrictedInformation</ext:ExtensionURI>
        <ext:ExtensionContent>
            <puf:PageroExtension>
                <puf:RestrictedInformation>
                    <puf:Key>InvoiceDeliveryMethod</puf:Key>
                    <puf:Value>ELEKTRONIK</puf:Value> 
                </puf:RestrictedInformation>
            </puf:PageroExtension>
        </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>   
  <!-- Code omitted for clarity -->
</Invoice>
----

==== First name and surname

If the buyer is a private person (uses TCKN), the first name and surname of the buyer should be included in specific elements.

*Example* +
_Invoice type code example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:AccountingCustomerParty>
        <cac:Party>        	
            <cac:PostalAddress>
                <!-- BT-50 Buyer address street-->
                <cbc:StreetName>Street Name</cbc:StreetName>
                <!-- BT-52 Buyer address City -->
                <cbc:CityName>City</cbc:CityName>
                <!-- BT-53 Buyer address postal code -->
                <cbc:PostalZone>00000</cbc:PostalZone>
                <cac:Country>
                    <!-- BT-55 Buyer address country code -->
                    <cbc:IdentificationCode>RS</cbc:IdentificationCode>
                </cac:Country>
            </cac:PostalAddress>
            <cac:PartyTaxScheme>
                <!-- BT-48 Buyer Vat Number if applicable -->
            	<cbc:CompanyID>98765432101</cbc:CompanyID>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:PartyTaxScheme>  
            <cac:Person> <!--1-->
                <cbc:FirstName>Buyer First Name</cbc:FirstName> 
                <cbc:FamilyName>Buyer Surname</cbc:FamilyName>
            </cac:Person>
        </cac:Party>
    </cac:AccountingCustomerParty>  
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> Note that the buyer's name is split into first name and surname separately. 

==== Tax category codes

Tax category codes for Türkiye are numerous and can be found here: https://pagero.github.io/puf-code-lists/#_tax_category_codes_turkiye[Tax category codes Türkiye^].


==== Tax scheme

In Türkiye there are various types of taxes in addition to the regular VAT (known as "KDV" in Türkiye). 
Another relatively common tax is what's known as "ÖTV", or Special Consumption Tax. This applies to sales of products such as alcohol, mobile phones, cars, and tobacco. In the event an invoice is applicable for this Special Consumption Tax, it needs to be indicated in the `cac:TaxScheme/cbc:ID` element on both line and header level.

Tax types other than VAT and SCT can also be supported in the Pagero Universal Format, but it is recommended you contact Pagero for further details. 

Note that the `cac:TaxScheme/cbc:ID` value should only be changed from 'VAT' if the tax being applied is *not* 'VAT'. 

*Example* +
_Special Consumption Tax example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:TaxTotal>
    <cbc:TaxAmount currencyID="TRY">45.00</cbc:TaxAmount>
    <cac:TaxSubtotal>
      <!-- BT-116 Sum of all taxable amounts subject to a specific tax category code and tax category rate. Currency in attribute currencyID (BT-5) -->
      <cbc:TaxableAmount currencyID="TRY">100.00</cbc:TaxableAmount>
      <!--  BT-117. The total VAT amount for a given tax category. Currency in attribute currencyID (BT-5) -->
      <cbc:TaxAmount currencyID="TRY">45.00</cbc:TaxAmount>
      <cac:TaxCategory>
          <!-- BT-118 Tax category code. -->
          <cbc:ID>9077</cbc:ID>
          <!-- BT-119 Tax category rate-->
          <cbc:Percent>45.00</cbc:Percent>
          <cac:TaxScheme>
              <cbc:ID>SCT</cbc:ID>
          </cac:TaxScheme>
      </cac:TaxCategory>
    </cac:TaxSubtotal>
  <cac:TaxTotal>
  <!-- Code omitted for clarity -->
</Invoice>
----

==== Internet Sales

If the invoice is the result of an online sale, extra information needs to be included in the invoice if it is applicable. 

|===
|Value |Description

|`Website URL`
|Website URL that online sale is processed from.

|`Payment date`
|The date the payment was or will be made.

|`Payment means`
|Supported codes are: +
48 (Credit/debit card) +
30, 31, 42, 58, 59 ("EFT/HAVALE", meaning money transfers) +
10 ("KAPIDAODEME", meaning payment at the door) +
68 ("ODEMEARACISI", meaning payment platform/forwarder like PayPal) +
ZZZ ("DIGER", meaning other type of payment. If other, it must be accompanied by explanation in `name` attribute.).

|`Payment platform`
|This is payment platform/forwarder name, used if payment is processed through a payment platform or forwarder like paypal. Mandatory if payment means code is 68 ("ODEMEARACISI")..

|`Shipment carrier tax id`
|Tax id (vkn) if shipment handled by company, individual id (tckn) if shipment handled by individual.

|`Shipment carrier name`
|Company name if shipment handled by company, first name and family name if shipment handled by individual.

|`Shipment date`
|The date of the shipment.

|===



*Internet Sales example* +
_Internet Sales example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <ext:UBLExtensions>
    <ext:UBLExtension>
        <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:RestrictedInformation</ext:ExtensionURI>
        <ext:ExtensionContent>
            <puf:PageroExtension>
                <!--If the invoice is the result of an online sale, the website URL is mandatory.-->
                <puf:RestrictedInformation>
                    <puf:Key>UBLTRWebsiteURL</puf:Key>
                    <puf:Value>www.exampleurl.com</puf:Value> <!--1-->  
                </puf:RestrictedInformation>
            </puf:PageroExtension>
        </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>   
  <!-- Code omitted for clarity -->
  <cbc:DueDate>2023-07-03</cbc:DueDate> <!--2--> 
  <!-- Code omitted for clarity -->
  <cac:PaymentMeans>
    <!-- BT-81 Payment means code. -->
    <cbc:PaymentMeansCode name="Payment platform name">68</cbc:PaymentMeansCode> <!--3-->    	
  </cac:PaymentMeans>
  <!-- Code omitted for clarity -->
  <cac:Delivery>        
    <cac:CarrierParty>
        <cac:PartyIdentification>
            <cbc:ID>1234543210</cbc:ID>  <!--4--> 
        </cac:PartyIdentification>
        <cac:PartyName>
            <cbc:Name>Carrier Party Name</cbc:Name>  <!--5--> 
        </cac:PartyName>
    </cac:CarrierParty>
    <cac:Despatch>
        <cbc:ActualDespatchDate>2023-07-03</cbc:ActualDespatchDate>  <!--6--> 
    </cac:Despatch>
  </cac:Delivery>
  <!-- Code omitted for clarity -->
</Invoice>
----
<1> Website URL that online sale is processed from. 
<2> Payment date. 
<3> Note the use of the attribute `name` to specify the payment platform. This is mandatory if the payment goes through a payment platform such as PayPal and others (code 68). 
Otherwise it is OK to omit the attribute. 
<4> This is the tax id of the shipment carrier. 
<5> This is the name of the shipment carrier. 
<6> This is the shipment date. 

